### ISSUE TITLE
objectMustContainText triggered even if aria-label used

### ISSUE THREAD

**Issue by robfentress** [ucfopen/UDOIT#101]
The objectMustContainText rule triggered even if `aria-label` used to provide alternative text for the `<object>`.

![screen shot 2016-02-24 at 4 10 15 pm](https://cloud.githubusercontent.com/assets/9356499/13301125/5a4fc86e-db11-11e5-829f-148454cccdd7.png)

**Comment by robfentress** [comment]
I've since found that, though, technically, using aria-label for alternative text for objects is okay, the support for this is inconsistent in Windows-Eyes and NVDA with Firefox, so the case for changing this one is diminished.

**Comment by robfentress** [comment]
Correction again: When I used a real URL for the data source and set the width and height, NVDA worked fine, so I guess the issue comes down to whether you think Window-Eyes has enough market share to warrant inclusion.  For me, Window-Eyes crashes constantly, so I find it hard to believe it is used as much as the [WebAim survey](http://webaim.org/projects/screenreadersurvey6/) suggests, but I guess it is the best we've got.

**Comment by jasonmatos23-git** [comment]
Closing because changes to 2.8 had been merged.
