### ISSUE TITLE
imgAltIsDifferent triggered even if aria-label used

### ISSUE THREAD

**Issue by robfentress** [ucfopen/UDOIT#105]
The imgAltIsDifferent rule is triggered even if `aria-label` is used to provide alternative text for an `<img>` tag that has an `alt` attribute set to the file name.

![screen shot 2016-02-24 at 4 24 56 pm](https://cloud.githubusercontent.com/assets/9356499/13301489/2c69df5a-db13-11e5-81ee-5158e66d4443.png)

**Comment by robfentress** [comment]
You also may be interested in the [thread from a similar bug report](https://github.com/squizlabs/HTML_CodeSniffer/issues/156#issuecomment-191591085) I made to HTML_CodeSniffer.

**Comment by bagofarms** [comment]
I know this is 5 years too late, but similar to the response from HTML_CodeSniffer, I don't believe this is a false positive.  `aria-labelledby` and `aria-label` appear to be for labels rather than a text equivalent.
