### ISSUE TITLE
imgAltIsDifferent triggered even if aria-labelledby used

### ISSUE THREAD

**Issue by robfentress** [ucfopen/UDOIT#106]
The imgAltIsDifferent rule is triggered even if `aria-labelledby` is used to provide alternative text for an `<img>` tag that has an `alt` attribute set to the file name.

For instance, the following fails, when it shouldn't:

```
<p><img src="x.jpg" aria-labelledby="monkey"/></p>
<div id="monkey">My monkey</div>
```

![screen shot 2016-02-24 at 4 27 57 pm](https://cloud.githubusercontent.com/assets/9356499/13301573/9cc9866a-db13-11e5-93da-98828f527e27.png)

**Comment by bagofarms** [comment]
I know this is 5 years too late, but similar to the response from HTML_CodeSniffer, I don't believe this is a false positive.  `aria-labelledby` and `aria-label` appear to be for labels rather than a text equivalent.
