### ISSUE TITLE
UFIXIT offers to fix page in Files, but throws unhelpful error

### ISSUE THREAD

**Issue by robfentress** [ucfopen/UDOIT#108]
UDOIT scans HTML pages uploaded to the **Files** tool and offers to fix them with UFIXIT.  However, trying to do this doesn't work and results in an empty error message being displayed.

**Comment by bagofarms** [comment]
UFIXIT for files has been fixed.  I'm closing this issue and making a new one for improving the error messages that come back from UFIXIT.
