### ISSUE TITLE
Add disclaimer to default welcome text

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#116]
Add a disclaimer to the bottom of the default welcome text that reads:

Please Note:  This tool is meant to be used as a guide, not a certification.  It only checks for common accessibility issues, and is not comprehensive; a clean report in U**DO**IT does not necessarily mean that your course is fully accessible.  Likewise, the tool may indicate a possible accessibility issue where one does not exist.

**Comment by emilysachs** [comment]
Resolved in this commit https://github.com/ucfopen/UDOIT/commit/4815495455e78542714e076b77e893408d590f9e#diff-0c2c7c4d879752ee30b98fc11328c9fd
