### ISSUE TITLE
Implement Google Analytics Event tracking for scans and fixes

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#126]

**Comment by cooperfellows** [comment]
@bagofarms I'd be interested to know more about your plans for this. Are you looking to track changes made to courses as events? I'd be happy to help where I can if I know more about the end goal here. I've got a good amount of Analytics experience.

**Comment by bagofarms** [comment]
We haven't implemented this yet, and we probably won't.  Closing this in the interest of cleaning up the issues list.
