### ISSUE TITLE
tableDataShouldHaveTh triggered on table with correct headings

### ISSUE THREAD

**Issue by robfentress** [ucfopen/UDOIT#128]
Scanning a table that has headers still results in tableDataShouldHaveTh being triggered.  Basically, I think it is insisting that all cells on the first row be `<th>`, which is not right.  The first cell in that row should not be a `<th>`, because it is empty.  This is not flagged as an error with HTML_CodeSniffer, Axe, AInspector, nor WAVE.

![screen shot 2016-04-15 at 11 22 23 am](https://cloud.githubusercontent.com/assets/9356499/14566531/ed85059a-02fd-11e6-8f07-22dfc86eed4f.png)

**Comment by robfentress** [comment]
I take it back.  It looks like the advice on this is ambiguous and using `<td>` for that first empty cell [can cause problems in VoiceOver](http://accessibleculture.org/articles/2010/10/voiceover-and-tables-with-an-empty-first-header-cell/).  I've checked with the current version of VoiceOver, and this hasn't been fixed.  I'm not sure a full-on "error" is appropriate, but I would certainly not prioritize fixing this.  Sorry.

**Comment by bagofarms** [comment]
We have put a lot of work into tables over the years, and I believe this has been fixed.
