### ISSUE TITLE
Change Error HTML output for tableThShouldHaveScope

### ISSUE THREAD

**Issue by techrangerfj** [ucfopen/UDOIT#147]
When the error tableThShouldHaveScope is detected the current error html output is the single tag that raises the issue. Change it to the entire table the tag is enclosed in, in order to provide useful information to viewer for consideration, particularly if UFIXIT will be used.

**Comment by emilysachs** [comment]
Duplicate issue created here https://github.com/ucfopen/UDOIT/issues/259
