### ISSUE TITLE
Add Closed Caption detection for Vimeo

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#148]
This should work in a similar way to the YouTube detection that already exists.  If the video is private, Vimeo will pretend the video doesn't exist, so the code needs to fall back to being a suggestion.

This should also include adding a field to localConfig for the Vimeo API key.

**Comment by rebelaide** [comment]
`<?php
include_once('httpful.phar');
$vimeo_api_key = '';
$vimeo_uri = 'https://api.vimeo.com/videos/';
use Httpful\Request;
# 0 = No captions
# 1 = Captions in English
# 2 = No English Captions
$vimeo_id = '';
$vimeo_uri.$vimeo_id.'/texttracks';
$response = Request::get($url)
	->addHeader('Authorization', "Bearer {$vimeo_api_key}")
	->send();
$captiondata = $response->body->data;
$vimeo_captions = array();
$vimeo_captions_multiple = array("1", "2");
if (empty($captiondata)){
	array_push($vimeo_captions, "0");
} 
else {
	foreach ($captiondata as $key => $object) {
		$caption_language = $object->language;
		if ($caption_language == "en-US" or $caption_language == "en"){
			array_push($vimeo_captions, "1");
		} 
		else {
			array_push($vimeo_captions, "2");
		}
	}
}
array_unique($vimeo_captions);
sort($vimeo_captions);
if($vimeo_captions==$vimeo_captions_multiple){
	array_splice($vimeo_captions, 1);
}
?>`

**Comment by rebelaide** [comment]
`<?php
include_once('httpful.phar');
include_once('config.php');
use Httpful\Request;
$vimeo_id = '';
$url = $vimeo_uri.$vimeo_id.'/texttracks';
$response = Request::get($url)
	->addHeader('Authorization', "Bearer {$vimeo_api_key}")
	->send();
$captiondata = $response->body->data;
$is_English = False;
if (empty($captiondata)){
	echo "No captions";
} 
else {
	foreach ($captiondata as $key => $object) {
		$caption_language = $object->language;
		if ($caption_language == "en-US" or $caption_language == "en"){
			$is_English = True;
		} 
	}
}
?>`

**Comment by bagofarms** [comment]
This will need to include instructions on how to generate the Vimeo api key in the README.
