### ISSUE TITLE
Request: report.json with all possible errors for testing

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/UDOIT#153]
Im working on converting the remaining html output to use templates and could really use a report with all the errors for testing.  Seems important for other testing purposes too.

**Comment by techrangerfj** [comment]
File (extension changed from .imscc to .zip for github upload)
[dev-udoit-dev-joseph-f-08-export.zip](https://github.com/ucfcdl/UDOIT/files/259555/dev-udoit-dev-joseph-f-08-export.zip)

**Comment by bagofarms** [comment]
I think having a test course is good, but this issue isn't actually asking for that.  I'm going to close it.
