### ISSUE TITLE
Displaying UDOIT errors err'd on magic quotes

### ISSUE THREAD

**Issue by adrian-goetz** [ucfopen/UDOIT#155]
When displaying the errors in UDOIT, it hit this file and the ' caused it to populate all following errors inside this one - as in I had to expand the errors on this file to see all the others, and they were placed in the div with this file rather than having their own separate divs.

[Introduction to the American Presidency.txt](https://github.com/ucfcdl/UDOIT/files/268290/Introduction.to.the.American.Presidency.txt)

**Comment by emilysachs** [comment]
There is an ongoing issue similar to this in my Dev course as well (https://webcourses.ucf.edu/courses/1165124/) where it seems that an li tag in an error preview is being read as part of the structure, causing the enclosing li tag to close prematurely and messing up the structure of all subsequent errors up until the next page's results.

**Comment by bagofarms** [comment]
This seems to be fixed in the latest version.
