### ISSUE TITLE
Mobile:  Detect if a table or its cells have fixed width, make it throw a Suggestion

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#160]
Tables with fixed widths (or containing cells with fixed widths) might display incorrectly on tablets and phones, running off the side of the page and creating inaccessible content.  Try viewing this page on a mobile device, and remove the portions with a fixed width if necessary.

**Comment by bagofarms** [comment]
Double-check that this has been implemented, link it to this ticket, and close if appropriate.

**Comment by jasonmatos23-git** [comment]
Issue resolved by #274
