### ISSUE TITLE
Use of font icons problematic for dyslexic and blind users

### ISSUE THREAD

**Issue by robfentress** [ucfopen/UDOIT#166]
Some font icons used in UDOIT's reporting do not have text alternatives and/or do not degrade well if custom fonts used.  For instance, the "new window" icon beside the page name link in the report does not have alternative text and so no indication is given that a new window will open on clicking the link.  Also, even if alternative text is provided, the icon becomes inaccessible to some dyslexic users who may apply custom fonts to enhance readability using tools like the [FontChanger Chrome extension](https://chrome.google.com/webstore/detail/font-changer-with-google/jgjhhoglgjdklldfgoffdiaceffijeke).  This is also the case for the Error and Suggestions badges, though in those instances this is less important, since there are other cues as to what the information provided is relating to.  See generic placeholder rectangles in the screenshot below, when using FontChanger to change font to [OpenDyslexic](http://opendyslexic.org/).

![screen shot 2016-06-03 at 2 54 31 pm](https://cloud.githubusercontent.com/assets/9356499/15789997/fc1e5942-299c-11e6-8ae2-a340215de533.png)

I've tested the [strategy for making accessible font icons](https://www.filamentgroup.com/lab/bulletproof_icon_fonts.html) recommended by the Filament Group and it seems to work.  I'd model any fixes on that.

**Comment by bagofarms** [comment]
Thanks!  Marking this as a bug.

**Comment by bagofarms** [comment]
This issue will be irrelevant in UDOIT 3.0.0
