### ISSUE TITLE
Add configuration flag for using UDOIT behind load balancers

### ISSUE THREAD

**Issue by bedmison** [ucfopen/UDOIT#167]
We have UDOIT running behind f5 load-balancers. The f5s manage the HTTPS connections to the clients but connects to the servers in the pool behind the f5s is HTTP. This causes the OAuth handshake to fail, because Canvas is expecting the URL of the host to be https, but the servers are reporting http. 

We have gotten around this by fiddling in /lib/ims-blti/OAuth.php to make sure that OAuthRequest::from_request() always returns https as the scheme. This works, but is far from ideal. We would like a configuration flag (like host_behind_loadbal ) that would force the https scheme type if true.

**Comment by elijahgagne** [comment]
We've hit this issue as well

**Comment by bagofarms** [comment]
I'll leave this open because we will need to take a fresh look at it in 3.0.0

**Comment by bagofarms** [comment]
@bedmison  Are you still having this issue with 3.x?

**Comment by bagofarms** [comment]
Closing this issue due to lack of response.  If you still require this feature, please reopen it.
