### ISSUE TITLE
Initial preview for color contrast misleading

### ISSUE THREAD

**Issue by robfentress** [ucfopen/UDOIT#172]
The preview presented to the user for color contrast issues is misleading, if no background color has been specified.  For instance, if I have specified a light red as my foreground color, the error it throws assumes the default white background.  However, in the _initial_ preview (before clicking the U FIX IT button) the text is presented on the standard grey background of the panel.  The U FIX IT preview correctly places the text on a white background, but the initial preview does not, and this may be confusing.  I think they should both have the white background, when no background color has been specified.

![screen shot 2016-06-29 at 8 13 09 am](https://cloud.githubusercontent.com/assets/9356499/16451504/7730f840-3dd1-11e6-960c-d1fcbc1072df.png)

**Comment by bagofarms** [comment]
Fixed in #186
