### ISSUE TITLE
Permissions on report directories and files are more permissive than required

### ISSUE THREAD

**Issue by bedmison** [ucfopen/UDOIT#188]
in ./public/process.php:121-123 and 131, the /reports/<report run hash> folder and the report data files are created with world-writable permissions (777). This was flagged as a possible security issue in an audit we ran. Testing shows less permissive restrictions of 754 allow the report data to be saved, while restricting the access.

**Comment by emilysachs** [comment]
No longer relevant with changes in https://github.com/ucfopen/UDOIT/issues/242
