### ISSUE TITLE
False positive for "Avoid using color for emphasis"

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#196]
This code produces the issue:  <p><strong>** BEFORE SUBMISSION, CONSULT THE <a id="" class="" title="Assignment #2 Instructions" href="https://webcourses.ucf.edu/courses/1225176/pages/assignment-number-2-instructions" target="" data-api-endpoint="https://webcourses.ucf.edu/api/v1/courses/1225176/pages/assignment-number-2-instructions" data-api-returntype="Page">ASSIGNMENT INSTRUCTIONS</a>. **</strong></p>

**Comment by cooperfellows** [comment]
@bagofarms I can't get this code sample to trigger, can you confirm this is still a problem? Thanks.

**Comment by emilysachs** [comment]
Appears to no longer be an issue when testing https://github.com/ucfopen/UDOIT/tree/dev/v2.2.0 
The only suggestion triggered is "Avoid using styles for document structure" as it should be.
