### ISSUE TITLE
Poor Installation Setup Instructions

### ISSUE THREAD

**Issue by yalegria** [ucfopen/UDOIT#198]
Does anybody has a complete set of instructions in how to install on a local server?

I was able to setup Udoit using Heroku but I prefer to host the app on my own server. Although I was trying to follow the instructions in the README file, I think it just lacks the flow of the necessary steps.i.e After running php composer.phar install, then what?...

**Comment by bagofarms** [comment]
In your example, the next step would be to set up the database, which is the next section in the README. After that, you would configure UDOIT, which is the section after the Database Setup in the README.  All of the steps related to this project are in the README.

I admit that some of the steps could be written better, and we are taking steps to address them right now, but I am curious to hear about the specific deficiencies you have found.

**Comment by bagofarms** [comment]
The instructions have been updated, and I hope they help.  We will continue to improve the instructions as the project evolves.  I'm going to close this issue for now, but if you find any other issues with the instructions, please open a new issue.
