### ISSUE TITLE
Add detection for private/deleted/copyright violation YouTube videos

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#2]

**Comment by techrangerfj** [comment]
Do we want to trigger a single error for all 3 of these situations. What would you want the verbiage for the test to be?

**Comment by techrangerfj** [comment]
@bagofarms

**Comment by bagofarms** [comment]
@techrangerfj If we can make it one error, that would be best.  Make the title "Web-based video is unavailable".  The description should be "The following web-based videos are unavailable due to being made private or deleted."

**Comment by bagofarms** [comment]
This feature will be better served by #200
