### ISSUE TITLE
Tool breaks after first fix.

### ISSUE THREAD

**Issue by yalegria** [ucfopen/UDOIT#241]
I have three errors in a particular page. When I fix the first error with U FIX IT it works, then I try to fix the second error and a "Waiting for Udoit to Finish" message with a spinning wheel appears instead of Submit button. 

I checked the browser console and found this javascript error:

```
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.success (default.js?cachebuster=1487256182:409)
    at j (jquery-2.1.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.1.1.min.js:2)
    at x (jquery-2.1.1.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-2.1.1.min.js:4)
```

Any ideas? Thanks for your help

**Comment by bagofarms** [comment]
This sounds like an issue we fixed in the last month.  Could you tell me what version of UDOIT you are using?  If you downloaded it from our last release, you are using 2.1.0.  If you used Git to pull the latest version from Master, use `git log` and let me know what the latest commit is.

**Comment by yalegria** [comment]
This instance was installed using Heroku, and I would say I "clicked" the "Deploy with Heroku" around January.  Is there a way to find the version of UDOIT on Heroku?

**Comment by cooperfellows** [comment]
I recall that error occurring in January, we fixed that in 65aab63d, my guess is that you are using a version from prior to that fix being included. 

I suggest connecting your Heroku app to GitHub through their Deploy tab:
![image](https://cloud.githubusercontent.com/assets/6798541/23036976/bb4aa444-f452-11e6-99da-267bfe9ef47d.png)

This does require you have a forked version of UDOIT that is kept up to date, you can't deploy from someone else's repository. 

That way, you can choose the latest release for a manual deploy:
![image](https://cloud.githubusercontent.com/assets/6798541/23037067/12875a40-f453-11e6-82a6-89b7d7bcc529.png)

I would suggest spinning up a new Heroku instance as a test case though, I would not replace it this way if you are using it in production without first testing it elsewhere.

**Comment by bagofarms** [comment]
@yalegria did you get a chance to update UDOIT?  If so, are you still experiencing this issue?

**Comment by bagofarms** [comment]
Because there was no response for two weeks, I'm closing this issue.
