### ISSUE TITLE
Fresh install on test instance

### ISSUE THREAD

**Issue by aanders-emu** [ucfopen/UDOIT#244]
Hi,
I've successfully installed the LTI far enough so it renders correctly in our test Canvas instance. I even see it reacting differently in different courses; some courses cause it to scan pages faster or slower depending on the content.

This all seems well and like a good sign.

However at the end of the can, I receive a generic message: "UDOIT failed to scan this course."

I'm not sure what troubleshooting steps are next; is it a lti-host server problem, canvas-lti configuration problem, etc? Is there a log file I could check?

Any suggestions are appreciated.

**Comment by bagofarms** [comment]
I've heard from two other schools that are having this issue with Heroku right now.  Does it happen at the end of every course you scan?  What about when you only scan the Files area?  Another school reported that it only happened on Pages, but I'm not sure if their problem spanned multiple courses.  Could you [follow these instructions ](https://devcenter.heroku.com/articles/logging#log-retrieval) to get the logs from your instance?

Thanks!

**Comment by aanders-emu** [comment]
Yes, this happens at the end of each course scanned. Also, I get the feeling the scan is working to a point and then failing; scans for different objects across different courses fail at different intervals.

I've tried to scan only files and only pages to no avail.

Lastly, I didn't deploy this on Heroku; I manually installed on a Linux server following your main doc. Are there any native logging functions in the LTI or maybe a particular script I can capture some output and share?

Thanks.

**Comment by bagofarms** [comment]
UDOIT doesn't have any constant logging at this time.  We have a logging system that we use when we need to debug things, but it isn't logging all the time.

Take a look at your PHP error logs and post the relevant sections here.  It could help to generate the error through UDOIT, then immediately check the logs.

**Comment by cooperfellows** [comment]
I'd suggest additionally looking at the client side console and network tab
to see if there are any messages being returned from the web call but not
being displayed to the end user.

**Comment by Achesong** [comment]
I'm getting this error also.
I believe we're hitting some kind of timeout value. It seems to occur at 25 seconds consistently, getting the following error:

Request URL:https://<our_url>/public/process.php
Request Method:POST
Status Code:504 Gateway Time-out

I'm running Apache2 + PHP 7
[php.ini]
max_execution_time = 90
max_input_time = 120

[apache]
Timeout 300

No errors in the apache error log.
Here are a couple clips of the browser-side errors.

![screenshot from 2017-03-14 12-40-47](https://cloud.githubusercontent.com/assets/25969228/23914486/13ac442e-08b4-11e7-9d5c-f0a5bdf37e10.png)

![screenshot from 2017-03-14 12-39-22](https://cloud.githubusercontent.com/assets/25969228/23914216/4dcc96e6-08b3-11e7-8a12-9c76ff6a1407.png)

**Comment by bagofarms** [comment]
@Achesong Thank you for the extra info!  I will start digging in.  I feel like it might be a PHP 7 compatibility issue, but it could also just be an issue with our latest update.

**Comment by aanders-emu** [comment]
FYI, I've specifically installed with PHP 5.6. However, I think my issue may be a bit more mundane; a permissions issue.

> PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "[MY DIR]/config/log.log" could not be opened: failed to open stream: Permission denied'

Any suggestions? How can I run this with the tightest permissions?

**Comment by bagofarms** [comment]
@aanders-emu We have a user group on our server that contains all of our developers as well as the user that PHP uses.  We then make sure that the file is part of that group, and that the group permissions allow reading and writing.  On a unix-like environment, you should be able to set the permissions to "760" on the log file, as long as the file is also part of the group that includes the PHP user.

**Comment by bagofarms** [comment]
@aanders-emu I just created a new issue that should help prevent this problem for future installations.  Check it out:  #253 

Please feel free to suggest other checks we can add to the list.

**Comment by aanders-emu** [comment]
Thanks! This suggestion (adding that file to the specific group) worked perfectly!
