### ISSUE TITLE
"Using color alone for emphasis" suggestion false positive on bolded text

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#250]
The following code triggers the "Avoid using color alone for emphasis" suggestion:
```
<span style="color: #0000ff;"><strong>Course Objectives Met by this Assignment</strong></span>
```
Even though the text is already emphasized with `<strong>`

**Comment by emilysachs** [comment]
(Should be addressed once https://github.com/ucfopen/UDOIT/pull/243 is merged, will verify then)
