### ISSUE TITLE
Only display current alternative text for source in report

### ISSUE THREAD

**Issue by rebelaide** [ucfopen/UDOIT#252]
Instead of showing the entire source of the image tag, only display the alt source. This would be less confusing for non-technical users.

Current:

Line 4: <img src="https://webcourses.ucf.edu/courses/1003256/files/35767586/preview?verifier=rIIt0qB17kBolEwXOHpysv2iBuUKYiHv643CVihi" **alt="kids-tech-revised.jpg"** data-api-endpoint="https://webcourses.ucf.edu/api/v1/courses/1003256/files/35767586" data-api-returntype="File">

Proposed:

 alt="kids-tech-revised.jpg"

**Comment by mkattut** [comment]
I like this idea, but what about images that have null alt text?

**Comment by rebelaide** [comment]
Null is displayed as an empty alt attribute in the source.

Current:

Line 1: <img src="https://webcourses.ucf.edu/courses/1003256/files/35767586/download?verifier=rIIt0qB17kBolEwXOHpysv2iBuUKYiHv643CVihi" **alt=""** data-api-endpoint="https://webcourses.ucf.edu/api/v1/courses/1003256/files/35767586" data-api-returntype="File"> 

I think just displaying it as empty would be sufficient. 

Proposed:

alt = ""

The image would be still displayed in the preview box above the source code.

**Comment by emilysachs** [comment]
(Discussed in person)
Going to test out adding a similarly-styled box with just the alt text next to the Preview and Source boxes.

**Comment by bagofarms** [comment]
This feature will be present in 3.0.0 upon its release.
