### ISSUE TITLE
Bold text in error preview misleading

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#258]
From Michelle Tuten at Clemson:
> Is there something wrong with how my institution has installed UDOIT or is there really so much more bold font than the previous version? If it is necessary to have so much bold font, could the bold be removed from the preview of issues? I find the Avoid using color alone for emphasis error particularly confusing when the preview shows the font in a bold format.

![bold_issue](https://cloud.githubusercontent.com/assets/1225334/25153762/bd727c90-245b-11e7-8e8f-e6acdfe47d7a.PNG)

Solution:
Text within the "Preview" pane should not be bolded.  It should be presented exactly how it is displayed on the page.

**Comment by emilysachs** [comment]
I caught some unclosed bold tags in https://github.com/ucfopen/UDOIT/pull/248 that hopefully should resolve this issue.
