### ISSUE TITLE
Add preview of entire table for header scope

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#259]
From Michelle Tuten at Clemson:
> With the No row or column scopes declarations found in headers of the table error, could there be a third preview added called Context which would display the whole table row that contains the offending cell? I had a course where I remembered to designate the header cells, but forgot the scope, and without being able to look at the table to determine if the scope needed to be column, row, or both, I couldn't use the U Fix It button.
![header_scope](https://cloud.githubusercontent.com/assets/1225334/25153880/3e9570e8-245c-11e7-9e74-ffbfd76d666f.PNG)

Solution:
I'm not sure if a whole new panel should be created, or if we could change the preview panel to show the whole table with the appropriate header field highlighted.

**Comment by emilysachs** [comment]
To avoid confusion with possible table styling, the offending header is shown in the preview on a separate line above the full table.
