### ISSUE TITLE
Redesign ability to Collapse Errors

### ISSUE THREAD

**Issue by techrangerfj** [ucfopen/UDOIT#26]
Currently, when an error description is clicked within a UDOIT Report prior to being fixed, if UFIXIT is enabled for that error otherwise indefinitely, the first error collapses even if multiple instances of the error exists for that course related document (page, discussion, assignment, etc.). If UFIXIT is enabled for that error, similarly only the first error is collapsed, however, an additional error instance number is present when un-collapsed. See images for reference.

![screen shot 2015-08-25 at 4 52 33 pm](https://cloud.githubusercontent.com/assets/7559106/9479116/c4dadf6e-4b49-11e5-829c-b9820ebc37c5.png)

![screen shot 2015-08-25 at 4 53 25 pm](https://cloud.githubusercontent.com/assets/7559106/9479131/d8273aae-4b49-11e5-92e8-a472787d9845.png)

![screen shot 2015-08-25 at 4 54 09 pm](https://cloud.githubusercontent.com/assets/7559106/9479153/f18008a0-4b49-11e5-9da6-dc2785f4af43.png)

**Comment by iturgeon** [comment]
I'm fixing this in my current work with #152 because I'm cleaning up the html and converting it into templates atm.
