### ISSUE TITLE
Delete old report options

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/UDOIT#270]
We probably need to deal with trimming old data at some point.  Honestly, you'd have to be using UDOIT a lot to get there, but it's a potential problem if you have a limited db size or A LOT of users.

I'm not sure if we really want to decide on one option or give people multiple options.

I can think of several, add any that sound sane:

* Keep reports forever, your DBA will let you know when it's a problem
* Delete old records after a configurable age
* More advanced db insert that knows when storage is low and clears space
* Only keep x number of records, configurable of course.

**Comment by bagofarms** [comment]
The structure of UDOIT 3.x will change the way this works, negating the need for this.
