### ISSUE TITLE
aMustHaveTitle accessibility test not necessary

### ISSUE THREAD

**Issue by edtechdev** [ucfopen/UDOIT#281]
(Forgive me, I don't have UDOIT running. Please delete/ignore this if aMustHaveTitle is already disabled) There doesn't seem to be a basis for the aMustHaveTitle accessibility test.  Screen readers ignore the title attribute on links by default, for example.

The code for the test is on line 371 here: https://github.com/ucfopen/UDOIT/blob/master/lib/quail/quail/common/accessibility_tests.php

It's been requested to be removed from the quail library UDOIT uses, but development on quail has ceased for a long time now, so the issue is still open:
https://github.com/quailjs/quail/issues/363

W3C HTML5 recommends against using the title attribute:
https://www.w3.org/TR/html/dom.html#the-title-attribute

And here are a few articles about not using the title attribute in links for accessibility purposes:
https://silktide.com/i-thought-title-text-improved-accessibility-i-was-wrong/
http://www.mediacurrent.com/blog/dont-rely-title-attribute-accessibility-seo
https://www.paciellogroup.com/blog/2013/01/using-the-html-title-attribute-updated/
http://webaim.org/articles/gonewild/#title

On the quail github page, since they are no longer actively developing it, they recommend to use the axe library instead.  I don't see any evidence that the axe library tests for a title attribute in links:
https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md

**Comment by emilysachs** [comment]
Hi Doug, that test is indeed disabled for UDOIT and only exists in the code from the quail library. Thanks for the concern!
