### ISSUE TITLE
Add bulk actions for Links should contain text and Headings should contain text

### ISSUE THREAD

**Issue by rebelaide** [ucfopen/UDOIT#301]
Add option to automatically fix by removing empty tags for Headings should contain text.

**Comment by bagofarms** [comment]
This feature is still valid for UDOIT 3.x

**Comment by bagofarms** [comment]
While this seems like a good idea, I think the amount of time it would save users is negligible compared to the development time involved.  Additionally, there are a number of edge cases that would need to be considered when implementing this feature.  I'm going to close this.
