### ISSUE TITLE
Database Connection Error

### ISSUE THREAD

**Issue by msantiago-cgi** [ucfopen/UDOIT#308]
Hi, 
I'm trying to run UDOIT on an apache stack installed on UBUNTU 16.04. I've downgraded the php version to 5.6 and I do get the configuration xml page ok per the ONLY video tutorial i've seen. I can't seem to get past an error regarding the DB and the only information being spit out into the logs isn't helping as much as i'd hoped. I've googled and googled. I've checked all the obvious things like making sure the user has the right privileges and that the sql server is running. I've also tried both using "localhost" and "127.0.0.1" for host. i've tried manually imputing the information into the PDO in db.php and NOTHING seems to be even giving me a more nuianced error to track things down. Below is all i've gotten from the log.log in config folder.

`udoit.WARNING: E_WARNING: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known {"code":2,"message":"PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known","file":"/var/www/html/UDOIT-2.2.0/lib/db.php","line":7} []
[2017-09-29 11:37:33] udoit.ALERT: Fatal Error (E_ERROR): Call to a member function execute() on boolean {"code":1,"message":"Call to a member function execute() on boolean","file":"/var/www/html/UDOIT-2.2.0/bin/db_create_tables.php","line":50} []`

Absolutely any help would be appreciated. Many thanks, Mark.

**Comment by cooperfellows** [comment]
Can you check the servers /etc/hosts file? Sometimes this is a DNS issue. The error you are actually interested in looking into is:
`php_network_getaddresses: getaddrinfo failed: Name or service not known"`

I believe this means PHP can't find localhost or 127.0.0.1. Does your server only support IPv6? That could be why 127.0.0.1 did not work. 

Just some thoughts...

**Comment by bagofarms** [comment]
@msantiago-cgi Are you still experiencing this issue?

**Comment by bagofarms** [comment]
Closing for now.  If you are still experiencing this issue, let me know.
