### ISSUE TITLE
Save report as PDF failing

### ISSUE THREAD

**Issue by rdalhoff** [ucfopen/UDOIT#309]
We recently confuted a local server to run UDOIT.  The scan and display of the results works fine, but when someone clicks the "Save report as PDF" all that is displayed is a blank window.
I messed with the parsePdf.php file and found that the script never finishes.  It seems to die when the "$pdf->WriteHTML($html, 2);"  line is executed.  

Is here something special I need to do to locally make the download work?

**Comment by bagofarms** [comment]
Can you verify that mpdf is installed in the vendor directory?

**Comment by rdalhoff** [comment]
Yes it is there.  I have been putting ECHO statements in it to see where it is failing to go on.

Just a  wild guess, but In the mpdf.php file it appears to die when the header('Content-disposition: attachment; filename="' . $name . '"'); line is executed in the following part of the script:

case 'D':
                                        //Download file
                                        header('Content-Description: File Transfer');
                                        if (headers_sent())
                                                throw new MpdfException('Some data has already been output to browser, can\'t send PDF file');
                                        header('Content-Transfer-Encoding: binary');
                                        header('Cache-Control: public, must-revalidate, max-age=0');
                                        header('Pragma: public');
                                        header('Expires: Sat, 26 Jul 1997 05:00:00 GMT');
                                        header('Last-Modified: ' . gmdate('D, d M Y H:i:s') . ' GMT');
                                        header('Content-Type: application/force-download');
                                        header('Content-Type: application/octet-stream', false);
                                        header('Content-Type: application/download', false);
                                        header('Content-Type: application/pdf', false);
                                        if (!isset($_SERVER['HTTP_ACCEPT_ENCODING']) OR empty($_SERVER['HTTP_ACCEPT_ENCODING'])) {
                                                // don't use length if server using compression
                                                header('Content-Length: ' . strlen($this->buffer));
                                        }
                                        header('Content-disposition: attachment; filename="' . $name . '"');

**Comment by bagofarms** [comment]
Can you verify that your system has the software installed as noted in the requirements section of the [mpdf readme](https://github.com/mpdf/mpdf)?

**Comment by rdalhoff** [comment]
Crap.  The RHEL7 system comes with php 5.4 which I guess is okay with UDOIT expect for the mpdf part that requires 5.6 or higher.  I had all the required packages installer, but only for version 5.4  Guess will need to install 5.6 outside the usual RedHat install channel.

Thanks for pointing out something I just kept overlooking.

**Comment by bagofarms** [comment]
No problem!  I'm glad this came up, because we need to update our README to require PHP 5.6.  I didn't realize mpdf required that until today.

I'm going to close this for now.  Feel free to reopen if you are still having issues.

**Comment by eriko** [comment]
We switched to using remi for php on OL7 (RHEL7) derived. 
https://www.remirepo.net/

**Comment by rdalhoff** [comment]
After installing php 5.6 simple pdf downloads of old reports with no errors or suggestions work now.  However the Run Scan always fails now.  We get the  "UDOIT failed to scan this course" response.  When the Scan is run we see the progress messages of scanning Pages, scanning Syllabus, etc. come up, but the scan always fails.
Likewise the PDF down load of an old report that had errors/suggestions in it just gives a blank screen.

php56w-pdo-5.6.31-2.w7.x86_64
php56w-devel-5.6.31-2.w7.x86_64
php56w-opcache-5.6.31-2.w7.x86_64
php56w-gd-5.6.31-2.w7.x86_64
php56w-cli-5.6.31-2.w7.x86_64
php56w-mcrypt-5.6.31-2.w7.x86_64
php56w-5.6.31-2.w7.x86_64
php56w-intl-5.6.31-2.w7.x86_64
php56w-xml-5.6.31-2.w7.x86_64
php56w-bcmath-5.6.31-2.w7.x86_64
php56w-common-5.6.31-2.w7.x86_64
php56w-mysql-5.6.31-2.w7.x86_64
php56w-mbstring-5.6.31-2.w7.x86_64

**Comment by rdalhoff** [comment]
I tried to find a way to reopen this ticket, but did not find how.  I added a comment, but that still did not reopen it.
Randy

**Comment by bagofarms** [comment]
I guess you can't reopen issues.  I'm reopening it now.

Have you checked your web server's error logs to see if PHP is throwing any errors from process.php?

**Comment by rdalhoff** [comment]
Even though in /etc/php.ini I had the parm date.timezone = 'America/Chicago' set and php -i showed that the default was set to America/Chicago, the UDOIT code was complaining that the timezone was not set.
[root@canvasext ~]# php -i | grep zone
"Olson" Timezone Database Version => 0.system
Timezone Database => internal
Default timezone => America/Chicago
date.timezone => America/Chicago => America/Chicago

I finally inserted the command
date_default_timezone_set('America/Chicago');
at the top of the  ..../config/settings.php file.
That fixed the problem with the Scan not running.

However, I still cannot do a PDF Download of certain scan results with errors or suggestions in them.  I now get an error of  that the program cannot access 
..../vendor/mpdf/mpdf/ttfontdata/dejavusansmono.GDEFdata.php

I am trying to find the dejavusansmono files that the system wants.

**Comment by bagofarms** [comment]
I've found that sometimes the ttfontdata folder doesn't have the correct permissions, blocking PHP from accessing it.  Check on the permissions for that folder and any parents.

**Comment by rdalhoff** [comment]
I just discovered that too. But that was after I did another mpdf install that put version 7 on.  That broke all sorts of things.  Now in the process of trying to restore version 6.1.4.
Randy

**Comment by rdalhoff** [comment]
I finally had to go back to installing mpdf version 6.1.3 and make sure the tmp and ttfontdata folders were writable.  Looks like everything works now.  Thanks for your help.

**Comment by iturgeon** [comment]
Thanks for reporting back after you got it working.
