### ISSUE TITLE
Check for Captions for Inline Media

### ISSUE THREAD

**Issue by rebelaide** [ucfopen/UDOIT#314]
The Canvas API returns the embed code for inline audio and video in a video tag. The embed code contains a <track> tag if the media has captions.

A check can be developed for the existence of the track tag. This is similar to the YouTube integration. A preview of the video/audio can be shown in the report with the embed code.

Code returned with API:

With caption track:

    <p><video preload="none" class="instructure_inline_media_comment" data-media_comment_id="" data-media_comment_type="video" controls="controls" poster="" src="" data-alt=""><track kind="subtitles" srclang="en" src=".json" label="English (US)"></track>    
    </video>

Without caption track:

    <p><video preload="none" class="instructure_inline_media_comment" data-media_comment_id="" data-media_comment_type="video" controls="controls" poster="" src="" 
    data-alt=""></video>

**Comment by bagofarms** [comment]
I believe this is the same as #355 , and was fixed in #361 .  I'm going to close it.  You won't see this issue fixed on our production instance yet, since it hasn't been updated to 2.6.2 yet.
