### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by matthewsherman** [ucfopen/UDOIT#322]
Is there anyway to post a copy of the UDOIT documentation?  The canvas link seems to be throwning an error when trying to login in:

{"errors":[{"param":"server-error","msg":"There was an error"}]}

**Comment by bagofarms** [comment]
I'm also getting the same issue when I try to download it directly.  Please report the issue to Instructure (I will, too).  In the meantime, you can try importing the User's Guide through Canvas Commons into an empty Canvas course to view the content.

**Comment by cg923** [comment]
Just wanted to mention that I'm having the same issue.  Would love to get my hands on this.
