### ISSUE TITLE
Create admin interface for viewing reports/stats

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#335]
Create an admin interface using a separate placement of the LTI in the Account Navigation menu.  It should allow admins to do the following:

- View stats on number of reports generated, who is generating them, what courses they are associated with, and what the most common errors are
- Drill down to view individual reports
- View a list of users and deauthorize them to alleviate authentication issues.

Because it will be in the Account Navigation menu, it will only be visible to admins.

**Comment by cg923** [comment]
Hi there, me again.

I was just wondering if there was any progress on this?  It would be a great feature to be able to view reports without going into each course specifically, and to be able to grant/ungrant the permission to see individual reports or an admin interface.

**Comment by bagofarms** [comment]
A fair amount of work has already been done on the admin interface.  I'll add a description to outline the features.  Thanks for the suggestions!  We'll take a look and see what we can do.
