### ISSUE TITLE
Check Captions for Rich Content Editor Video 

### ISSUE THREAD

**Issue by rebelaide** [ucfopen/UDOIT#355]
Check if caption track exists for media (audio and video)[recorded/uploaded through the Rich Content Editor](https://community.canvaslms.com/docs/DOC-13055-4152719746)

The API will return the following html code for a video uploaded through the record/upload feature:

Video without captions:

`<p><video preload="none" class="instructure_inline_media_comment" data-media_comment_id="123456" data-media_comment_type="video" controls="controls" poster="http://example.com" src="http://example.com/course_id/media_download?entryId=123456&amp;media_type=video&amp;redirect=1" data-alt=""></video></p>`

Video with Captions

`<p><video preload="none" class="instructure_inline_media_comment" data-media_comment_id="123456" data-media_comment_type="video" controls="controls" poster="http://example.com" src="http://example.com/course_id/media_download?entryId=123456&amp;media_type=video&amp;redirect=1" data-alt=""><track kind="subtitles" srclang="en" src="https://example.com/media_objects/123456/media_tracks/1000.json" label="English (US)"></track></video></p>`

Add support for the audio tag as well. 

A video without captions should be an error. Audio without captions should be a suggestion.

**Comment by seanlh** [comment]
Using UCF's Canvas LMS, I uploaded a video and added subtitles. The page only has this code:
`<p><a id="media_comment_m-3Xf1Ymwto5jLX4ck6SMAvHfxwDdStbso" class="instructure_inline_media_comment video_comment" data-media_comment_type="video" data-alt=""></a></p>`

**Comment by seanlh** [comment]
After @rebelaide cleared some things up, currently trying to integrate it into the accessibility tests.
Note for me: Need to refactor code to not check for vimeo/youtube by attribute because canvas' media id will not work for all video tag cases.

**Comment by bagofarms** [comment]
This feature was added a while ago, but we never closed the issue.  I modified the text to make it more descriptive and pointed the user to https://community.canvaslms.com/docs/DOC-13043 for remediation.
