### ISSUE TITLE
Align with WCAG 2.1 Standards

### ISSUE THREAD

**Issue by rebelaide** [ucfopen/UDOIT#371]
The finalized recommendation for WCAG 2.1 was published today: https://www.w3.org/TR/2018/REC-WCAG21-20180605/

Review and revise as appropriate.

**Comment by bagofarms** [comment]
Here's an overview of the differences:  https://www.w3.org/TR/WCAG21/#new-features-in-wcag-2-1

**Comment by AlanFCMV** [comment]
I have gone through the list of differences and evaluated each with regards to how they concern UDOIT. In summary, I do not believe any of the differences are relevant to this application.

1.3.4 Orientation (AA)
Device orientation can not be detected programmatically from scanning of an html file.

1.3.5 Identify Input Purpose (AA)
Canvas does not allow for the creation of functional input elements.

1.3.6 Identify Purpose (AAA)
This is already accounted for to the extent that it is possible for our application. For example, the application already confirms that paragraphs are not used in place of headings, or that images without alt text are properly marked as decorative, among others.

1.4.10 Reflow (AA)
This is device-dependent, as well as the responsibility of the canvas viewer itself.

1.4.11 Non-Text Contrast (AA)
Scanning graphical elements such as images is out of scope for the application as it currently stands. We do not possess the infrastructure to actively scan images, as this would involve downloading each image individually. This would greatly harm the performance of the application as it stands.

1.4.12 Text Spacing (AA)
The text spacing for a canvas page is determined by canvas.

1.4.13 Content on Hover or Focus (AA)
There is not a way for us to detect this programmatically from course content.

2.1.4 Character Key Shortcuts (A)
This is not within the scope of our application.

2.2.6 Timeouts (AAA)
This is not within the scope of our application.

2.3.3 Animation from Interactions (AAA)
Animations are not supported course content by the canvas lms.

2.5.1 Pointer Gestures (A)
This is not within the scope of our application. Device functionality can not be determined from the course content.

2.5.2 Pointer Cancellation (A)
This is not within the scope of our application. Device functionality can not be determined from the course content.

2.5.3 Label in Name (A)
This is not within the scope of our application.

2.5.4 Motion Actuation (A)
Device motion is not within the scope of our application.

2.5.5 Target Size (AAA)
Identifying screen area taken up by clickable elements is beyond the scope of our application.

2.5.6 Concurrent Input Mechanisms (AAA)
Canvas does not allow for the creation of functional input items in its content.

4.1.3 Status Messages (AA)
Status messages are beyond the scope of our application, as it does not relate to course content.

**Comment by bagofarms** [comment]
I'm going to close this since there are no actions to take on it right now.
