### ISSUE TITLE
504 Gateway timeout during Canvas App creation

### ISSUE THREAD

**Issue by cg923** [ucfopen/UDOIT#373]
Hi there,

This may not be a UDOIT issue, but Canvas support had no idea what I was talking about.

We are using canvas hosted on Instructure, but UDOIT hosted on our own webserver.  I have installed UDOIT correctly, as far as I can tell.  At least, I have followed the instructions without running into any issues, until the last step.

I fill in the Consumer key, secret, and correct path to the config file (https://starling.middlebury.edu/public/udoit.xml.php), but when I hit submit nothing happens.  Looking in the console, the call to Canvas's API (https://middlebury.instructure.com/api/v1/accounts/1/external_tools) times out with a 504 and an "Unexpected end of JSON input" error.

I'm happy to provide any other details that might be relevant.  Does anyone have any ideas?

Thank you!

**Comment by bagofarms** [comment]
I think this is a problem with your web server.  When I try to view the link to your xml file, I also get a timeout.  Are you sure your web server is accessible to people outside your network?

**Comment by cg923** [comment]
> Are you sure you web server is accessible to people outside your network?

No, I am not sure!  I will have to check in on that.  Didn't even occur to me.  Thank you!

**Comment by cg923** [comment]
Indeed, that was the trick.  Thanks again!

**Comment by bagofarms** [comment]
No problem!
