### ISSUE TITLE
README Permissions Section

### ISSUE THREAD

**Issue by Dani21** [ucfopen/UDOIT#387]
There's a section of the README that says...

> ### Storage for Reports
> 
> Make sure the reports directory in the root of UDOIT is writable by your webserver. UDOIT saves generated reports here for easy retrieval. You may have to change the user, group, or permissions to get this working (sorry we can't be more specific, it varies greatly depending on your environment).

There are other locations that need to be writable though, from what I've found so far, these include:

- vendor/mpdf/mpdf/ttfontdata
- vendor/mpdf/mpdf/tmp
- public/reports
- config

**Comment by bagofarms** [comment]
Great point!  We'll have to make a note that the mdpf permissions need to be taken care of AFTER composer is run.
