### ISSUE TITLE
Make Dockerfile production-ready and create Helm chart for Kubernetes installation

### ISSUE THREAD

**Issue by smoyer64** [ucfopen/UDOIT#388]
This issue is a list of tasks that we're working on to deploy UDoIt on PSU's Kubernetes infrastructure.  WIP at https://github.com/PennState/UDOIT.

- Docker
  - Environment variables for:
    - Database selection
    - Database connection
    - PHP version
    - LTI configuration

- Helm (Kubernetes) 
  - Default configuration values
    - Docker environment variables above
    - Optional DB in a container
    - Number of deployed PHP pods
    - ?
  - Optional DB container
  - Templates - TBD (PHP example at https://github.com/helm/charts/tree/master/stable/phpbb)

Potentially related to #365

@anf107 @apn114 @ussmith

**Comment by bagofarms** [comment]
Pull request #366 is supposed to fix issue #365 , so it might be worth a look.
