### ISSUE TITLE
Pull Quail library out and include it with composer

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/UDOIT#40]
The quail library included in UDOIT is a modified version of a very old version of QUAIL.

I've exported the google code version here https://github.com/iturgeon/quail-lib 

I'd like to update that library it with the changes UDOIT has added and move it to a composer installed library.

Bonus level 2: QUAIL has a few dependencies of it's own, investigate if those can be plucked out.

https://github.com/DaveChild/Text-Statistics under `core/quail/common/services/readability/php-text-statistics/`

https://github.com/git-mirror/simpletest is under `core/tests/simpletest`

**Comment by bagofarms** [comment]
This will be achieved with 3.0.0
