### ISSUE TITLE
Adobe Reader unable to open PDF

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#407]
Sometimes, when a PDF is generated by clicking the button in the UDOIT interface, Acrobat Reader or Pro will not open the file because "there are errors in the document".  Usually, the file can be opened in the Chrome PDF reader or Preview on Mac OS.

This issue is inconsistent and requires more testing to determine the cause.

**Comment by davidengebretson** [comment]
I consistently get this error… Can’t open in Adobe reader, Chrome, or Preview.

**Comment by bagofarms** [comment]
Closing this due to age and the possibility that it may have been resolved by #309  or #475 / #487
