### ISSUE TITLE
Add ability to pass options to PDO constructor

### ISSUE THREAD

**Issue by dstepe** [ucfopen/UDOIT#408]
We need to use a CA cert file when connecting to our enterprise MariaDB instance. This requires passing an array of options to the PDO object constructor.

References:

http://php.net/manual/en/pdo.construct.php
https://stackoverflow.com/questions/9738712/connect-to-remote-mysql-server-with-ssl-from-php

It looks like the changes should be minimal. I've forked the project and will work on a PR for this.

**Comment by bagofarms** [comment]
Fixed by #418
