### ISSUE TITLE
Make job_queue table name configurable

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#411]
It should be configurable just like the `users` and `reports` tables in https://github.com/ucfopen/UDOIT/blob/master/config/localConfig.template.php#L44

Also, update all references to job_queue in locations such as this:  https://github.com/ucfopen/UDOIT/blob/master/lib/UdoitJob.php#L79

**Comment by bagofarms** [comment]
I fixed the issues (they were just linting errors) and merged in the code.  Thank you so much!

**Comment by amarjitsingh52922** [comment]
actually  just browsing github and found it :)
