### ISSUE TITLE
Unlisted videos should be suggestions

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#431]
Unlisted, private, and deleted videos are currently treated the same (with a "Manual verification required" message next to them).  Instead, use the `https://www.googleapis.com/youtube/v3/videos` endpoint to determine the `status` of the video.  If it is `unlisted`, ignore it for the `videosEmbeddedOrLinkedNeedCaptions` error and instead modify the `videoUnlistedOrNotFound` error in #255 to be a suggestion.

**Comment by bagofarms** [comment]
Related to #200 and #2

**Comment by bagofarms** [comment]
To Do:  Check Vimeo's documentation for the equivalent.

**Comment by jrsilveti** [comment]
Done. Pull request #438 has this fix.
