### ISSUE TITLE
Incorrect summary report shown

### ISSUE THREAD

**Issue by apn114** [ucfopen/UDOIT#446]
I came across this issue during my testing of UDOIT.

**Scenario:**
- I log into my LMS and browse to UDOIT in two courses in separate tabs
- Let's assume the courses are named A and B
- I run UDOIT in course A
- A summary report appears with the title 'Report for A', as expected
- Then I go to course B and run UDOIT without refreshing the page
- The summary report appears as 'Report for A' which is not what I'm expecting
- Refreshing the page and running the scan again shows the correct report titled 'Report for B'

**Comment by ssilverm** [comment]
Having run into this with other LTI's, it sounds like a session issue where the "current" course is stored in a session variable.   When the page runs without a full refresh it only has whats in the session value, which is Class A.

We might be able to look at the referrer and if the current course id differs from the referrer course id we do a refresh?

**Comment by bagofarms** [comment]
Thanks for bringing this to our attention.  We have been able to recreate the issue and are investigating how we could mitigate it.

**Comment by bagofarms** [comment]
This will be fixed by UDOIT 3.x, as it completely changes the way sessions are handled.  This issue will not be fixed in UDOIT 2.x.
