### ISSUE TITLE
Chrome secure-by-default cookie policy

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#459]
Users have reported that the cookie settings in Chrome 80.0 (launching February 3rd) causes issues with UDOIT.  More info:  https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

Here's an example in PHP of how to implement this change:  https://github.com/GoogleChromeLabs/samesite-examples/blob/master/php.md

**Comment by bagofarms** [comment]
Some more details in #460

**Comment by cidilabs** [comment]
Here's what I've come up with for our other Cidi Labs products. It should work here as well.

`function setupSession($options)
    {
        $expire = isset($options['expire']) ? $options['expire'] : 0;
        $path = isset($options['path']) ? $options['path'] : '/';
        $domain = isset($options['domain']) ? $options['domain'] : NULL;
        $secure = isset($options['secure']) ? $options['secure'] : TRUE;
        $httponly = isset($options['httponly']) ? $options['httponly'] : FALSE;

        if (PHP_VERSION_ID < 70300) {
            session_set_cookie_params($expire, "$path; samesite=None", $domain, $secure, $httponly);
        } else {
            session_set_cookie_params([
                'expires' => $expire,
                'path' => $path,
                'domain' => $domain,
                'samesite' => 'None',
                'secure' => $secure,
                'httponly' => $httponly,
            ]);
        }
    }`

**Comment by bagofarms** [comment]
Nevermind, I have the code in my email notification.  It looks like the best place for this is in `config/settings.php`.  It shouldn't be too bad (famous last words).

**Comment by cidilabs** [comment]
Sorry, not sure where that file came from. Here's the intended patch.
[udoit_459.patch.txt](https://github.com/ucfopen/UDOIT/files/4060149/udoit_459.patch.txt)
