### ISSUE TITLE
Chrome v80 and secure cookies

### ISSUE THREAD

**Issue by cidilabs** [ucfopen/UDOIT#460]
Google Chrome v80 is changing its SameSite policy, which is causing problems among LTI tools in Canvas.

Khaled Musa of UMN has tested UDOIT with the new Google Chrome defaults and the tool failed to load.

![image](https://user-images.githubusercontent.com/46353870/72189608-85350700-33ba-11ea-93e6-d97a6aeee214.png)

The scheduled release for chrome 80 Is Feb. 3 based on the Chrome release page. You can test that behavior by typing Chrome://flags in the address bar and setting the 2 below options to enable:
SameSite by default cookies
Cookies without SameSite must be secure

**Comment by cidilabs** [comment]
Tagging @bagofarms on this...

**Comment by bagofarms** [comment]
Closing because it is a duplicate, but linking back from #459 because of the extra info and screenshot.
