### ISSUE TITLE
Unable to find /vendor/autoload on db-setup

### ISSUE THREAD

**Issue by elearningdave** [ucfopen/UDOIT#461]
When I run the db-setup command, I get the following error:

C:\htdocs\ws\udoit>php composer.phar db-setup
> php bin/run_database_migrations.php

Warning: require_once(C:\htdocs\ws\udoit\config/../vendor/autoload.php): failed
to open stream: No such file or directory in C:\htdocs\ws\udoit\config\settings.
php on line 9

Fatal error: require_once(): Failed opening required 'C:\htdocs\ws\udoit\config/
../vendor/autoload.php' (include_path='.;c:\php\includes') in C:\htdocs\ws\udoit
\config\settings.php on line 9
Script php bin/run_database_migrations.php handling the migrate event returned w
ith an error

  [RuntimeException]
  Error Output:

db-setup [--dev] [--no-dev] [--] [<args>]...

Any ideas? All files are present and correct from the zip download

**Comment by elearningdave** [comment]
Solved - the bit about installing Composer first was not in bold, which is why it got missed.

**Comment by bagofarms** [comment]
I'm glad you got it working.  We placed the the [Installing Composer Dependencies](https://github.com/ucfopen/UDOIT#installing-composer-dependencies) section before the Database Setup section in the README for this reason.  If there is an alternative format that you think would make this step more clear, feel free to submit a pull request

**Comment by elearningdave** [comment]
On a similar note, I got an error when running the composer install command on one of the files (I've lost the output from the command line sorry) where it was complaining that I didn't have GIT installed locally to pull one of the files. I'll have to rerun it on a different server to find out which file, but every other file came down fine.
I'm wondering if that's why, even on a small course (a couple of pages and 13 SCORM packages) it is still sat on the green spinning bar saying ' Scanning (0 items left)

**Comment by bagofarms** [comment]
It's possible that there was an error with the scan.  From the root directory of UDOIT, you can run `tail -f config/log.log` in your terminal before running the scan to see if any error messages show up.

**Comment by elearningdave** [comment]
I'll reinstall the code on our side (Heroku was failing to detect the app.json file in your repo) when you release 2.6.0 - and try again then.
I need to find a windows alternative to tail -f as this isn't a linux server.
Pleased I got this far just on instructions and some guesswork though as the people we heard locally were using it don't have any of the tech knowhow from the install left to support us here.

**Comment by bagofarms** [comment]
I did a little bit of searching, and people are reporting that you can use `tail -f filename` in Windows Powershell now.  I don't have a windows machine to test it on, though.

**Comment by bagofarms** [comment]
I'm going to close this issue, since you were able to get it working.  Please feel free to open a new issue if you're unable to fix the stalling scan after looking at the logs.
