### ISSUE TITLE
What should oauth2_id be?

### ISSUE THREAD

**Issue by elearningdave** [ucfopen/UDOIT#462]
There is nothing in the documentation stating how we set or deduce this on the canvas.
We have tried:

- leaving it blank
- using consumer_key value
- using the number above the button that shows the developer key (116370000000000007 in our case)

How do we do this last bit?

**Comment by elearningdave** [comment]
UPDATE we fixed this by using the 3rd option. But on the LIVE site. I was trying this in our test canvas site, which must have some extra restrictions on it (we know email notifications are disabled, but will have to investigate what else)

**Comment by bagofarms** [comment]
I'm glad you found the ID.  The documentation for this was lacking, but the 2.6.0 version of UDOIT (releasing this week) has more detailed documentation that is up-to-date with the current Canvas UI.
