### ISSUE TITLE
Always using the email address of the API key-associated user

### ISSUE THREAD

**Issue by elearningdave** [ucfopen/UDOIT#463]
When I load the tool on a new canvas session, canvas asks to do the authorization as the email address of the system account I created the API key under. e.g. we used a manual service account on canvas with email address abc@ourcollege.ac.uk, but while logged in to canvas as my personal user (e.g. email address myname@ourcollege.ac.uk).
It sounds like an auth thing has gone wrong - but we've setup other LTIs with a shared developer key under the same service account on canvas, and those LTIs have successfully established which user profile is using it. I definitely followed the API key setup instructions / config file part correctly.
Looking in the user table in the udoit database, it has picked the correct user_id for me not the service account - it just seems a mismatch. Any ideas? I don't mind sending screenshot(s) privately.

**Comment by bagofarms** [comment]
I've never seen that happen before.  You should be able to create the Developer Key (confusingly called an API key in Canvas) with any admin account.  Take a look at the new instructions for 2.6.0:  https://github.com/ucfopen/UDOIT/tree/dev/v2-6-0#canvas-oauth2

Go through those and make sure the Developer Key is set up correctly.

**Comment by elearningdave** [comment]
We've done the make a developer API key before, and it was no problem. I checked your new instructions, they are the steps I did.
The most important thing is that it picked up the canvas user ID and showed the name of the user who's logged in, in the authorization page. I'll email you a screenshot at some point.

**Comment by elearningdave** [comment]
I have no idea what I did 'wrong' last time, but I did a full reinstall of the server side code (still v2.5), and it is now showing my name and email address when I authorize the app when running the LTI in a course. Will see if it fixes the other issues...
