### ISSUE TITLE
Report not displaying (including View Old Reports)

### ISSUE THREAD

**Issue by elearningdave** [ucfopen/UDOIT#464]
I have got reports running (by looking in the job_queue sql table, I see the passes of the scan running and a report stored). But:
1) it is not updating the green button to tell the user which part it is doing (assignments, discussions, etc)
2) it is not counting down how many are left (e.g. 7 at the start if you tick all of them)
For both 1 and 2, it is just showing the word Scanning...
3) when it finishes, the button updates to Scanning... (0 left to scan), the database shows the right number of 'finished' rows, but it does not show the report below the green button.
Also, when you click View Old Reports it is not picking up the old ones.

Nothing in the reports sql table either (it is present). Also, nothing showing in logs (I have tail -f running, thanks for looking that up).

Any ideas what's been missed? TIA

**Comment by elearningdave** [comment]
Other detail, nothing in the reports table either (it is present)

**Comment by elearningdave** [comment]
Also, nothing showing in logs (I have tail -f running, thanks for looking that up)

**Comment by elearningdave** [comment]
Update - I just refreshed the tail -f process and it showed me a bunch of stuff. Some were INFO: Requesting... lines which I assume is part of the scan. Several were this though:
_udoit.INFO: Loading saved reports_
Which I assume is where I try to load the View Old Reports tab

**Comment by bagofarms** [comment]
You said you're using Windows Server, correct?  I don't have that environment to test on, so it will be very difficult for me to debug.  There was one school back in 2015 that tried to use UDOIT with Windows Server, and was unable to get it working, but I was hoping things had improved with the later versions of PHP.

**Comment by elearningdave** [comment]
I don't have any linux servers with AMP on, to try running it on there. IT might provision a test one if I ask nicely. The linux server I have runs its services under Jetty (on port 443), and that's a live service I don't want to muck about it.
I tried Heroku but it said it couldn't find app.json when I clicked the one-click install on the readme page - I'll log a new issue if you want, but if you can check that's working from your end I'll try it again (I did email them but not had an answer so far)

**Comment by elearningdave** [comment]
A full reinstall of the code (now being wiser of the order to do what in) has fixed it
