### ISSUE TITLE
Install error for symfony2

### ISSUE THREAD

**Issue by elearningdave** [ucfopen/UDOIT#465]
Here is the error, from when I do 'php composer.phar install'. ALL other dependencies download/load OK (I've done slightly above/below the break point for safety):

 _- Installing squizlabs/php_codesniffer (3.3.1)
   Loading from cache

 - Installing escapestudios/symfony2-coding-standard (dev-master 2a8358b)
   Cloning 2a8358b3a17dcb9f3e2889b70a257106aa37f6f4
   Failed to download escapestudios/symfony2-coding-standard from source: Failed to clone https://github.com/djoos/Symf
ny-coding-standard.git, git was not found, check that it is installed and in your PATH env.

git' is not recognized as an internal or external command,
perable program or batch file.

   Now trying to download from dist
 - Installing escapestudios/symfony2-coding-standard (dev-master 2a8358b)
   Loading from cache_

**Comment by bagofarms** [comment]
I see it trys to install symphony2-coding-standard again at the end of the snippet.  Does it ever successfully install?  Composer usually tries to install things with Git first, then falls back to HTTPS, but you may need to install Git on the server to get this to work.

**Comment by elearningdave** [comment]
According to the log, there is no specific error saying that library doesn't actually install.
I'm thinking getting Heroku working will be easier, but if we can't get that to work for us then I will ask for a small linux vm to try

**Comment by elearningdave** [comment]
The report running suggests it installed ok? Or is there a specific thing on a course that it looks for, that I can deliberately try and test hitting udoit with?

**Comment by bagofarms** [comment]
That package is not used by UDOIT itself.  Rather, it's used by the code sniffer that tells us developers if we wrote code that did not meet our standards.  You can run `php composer.phar install --no-dev` instead, and it will remove all of the developer-focused packages that are not used by UDOIT itself.

Now that you bring this up, I realize we need to update the README to reflect this information.

**Comment by elearningdave** [comment]
Also on a readme note, the Mysql user claims to need alter and grant. That is NOT enough to create the tables when you run the db-setup command. I had to add CREATE permission to that use for the duration of the db-setup task.
