### ISSUE TITLE
No spacing on the PDF report (enhancement)

### ISSUE THREAD

**Issue by elearningdave** [ucfopen/UDOIT#467]
Looking at a PDF export of a report, I see the following:

_**8 Errors**
6Links should contain text
1Headings should contain text
1No closed captions found.
**148 Suggestions**
5Avoid using styles for document structure
1Content length should not exceed 3000 words.
2Link text should be descriptive
138Avoid using color alone for emphasis_

It would be great if there was a space between all the individual item numbers and the label for them (I notice there is one on the subheadings, but the items underneath the subheadings don't have a space after the Span tag:
_<li class="list-group-item text-danger title-line">
<span class="badge badge-error">6</span>Links should contain text</li>_

I can't trace where this is rendered so far, so can't do it myself.

**Comment by bagofarms** [comment]
The PDF output could definitely use some touching up.  Thanks!

**Comment by bagofarms** [comment]
Changes to this display are handled through the PDF css:  https://github.com/ucfopen/UDOIT/blob/master/public/assets/css/pdf.css

**Comment by AlanFCMV** [comment]
Issue resolved
