### ISSUE TITLE
Protect admin.php

### ISSUE THREAD

**Issue by elearningdave** [ucfopen/UDOIT#468]
Whilst this doesn't include student data (so not a GDPR risk), I would suggest having an admin authentication method would be a good idea. I may protect ours with LDAP or Shibboleth, using Apache modules.

**Comment by bagofarms** [comment]
The admin panel is accessible only to Canvas accounts that are Administrators or higher, so I don't see a need in adding extra authentication.  Did you find that restriction insufficient at your institution?

**Comment by elearningdave** [comment]
I couldn't find a note of that in the documentation. Or any documentation on the admin panel (beyond the statement that it's a draft, so presumably more documentation is forthcoming in the future?).
I got a regular tutor to try it for me, and she's confirmed it works. Another one for the documentation list!

**Comment by bagofarms** [comment]
Thanks for testing it with a tutor.  When you say "it works", do you mean that she was able to view the admin panel and access the data in it even though she's not an Administrator?  If so, what path did she take to get to the admin panel?

**Comment by elearningdave** [comment]
To clarify - she was NOT able to open the admin page. It came up with an error mentioning the word admin (I can't remember it exactly, but it did stop her doing before even offering a form to access data)
