### ISSUE TITLE
Misleading error when Syllabus body is empty

### ISSUE THREAD

**Issue by cronek** [ucfopen/UDOIT#490]
When a course Syllabus has no description text, the scan report produces this error:
"Due to LMS limitations, UDOIT is unable to scan this section. Read our FAQ for more information."

The message links to a section of the FAQ describing how to turn on Includes when scoping the developer key.  However, scoping is not being used.  Turns out that just adding a description (body) to the Syllabus allows the scan to proceed without the error.

Suggest the scan just show a Success with count 0 of 0.

**Comment by bagofarms** [comment]
Thanks for reporting this.  The code is checking to see if the `syllabus_body` field exists in the returned object.  I guess I assumed that the Canvas API would return an empty `syllabus_body` if the syllabus was empty. We’ll take a look and see if we even need this check anymore.
