### ISSUE TITLE
scanning course hangs on spinner

### ISSUE THREAD

**Issue by masantiago-wpi** [ucfopen/UDOIT#499]
Hello,
I was asked to update the installation of UDOIT our canvas instance had installed from about 2 years ago. I got it to the point where on loading a course it asks for permission and gives me the scanning screen with checkboxes but after hitting the scan button it simply stays spinning. There's no timeout error, or other visual cue that something is wrong. 

In the process of upgrading UDOIT i had to also upgrade form php5.6 to 7.1 but i confirmed that the settings on the php.ini file match now. 

any suggestions on how to track down this issue would be appreciated.

**Comment by bagofarms** [comment]
Definitely start with checking the logs.  If you are using Heroku, you can log in to Heroku, Select your instance of UDOIT, then use the drop-down in the top-right to view the logs.  If you're hosting it yourself, take a look at `config/log.log`.  You can also `tail -f config/log.log` from the root of the UDOIT project before clicking the "Scan this course" button to see what happens in real-time.

**Comment by masantiago-wpi** [comment]
Thank you VERY much.  it gave tons of useful information. Looks like a database error is part of the problem.

**Comment by bagofarms** [comment]
Awesome!  Please post your solution here when you figure out what's going on.

**Comment by masantiago-wpi** [comment]
I backed up and dropped all the tables to start fresh by going through the installation process. I'm still getting the same DB errors though. These are just the first 3. Once i did this, i was prompted to allow udoit to work in canvas and once i hit the scan button this is the output from tail. Interestingly the user table had two new rows with refresh tokens so something is connecting to db fine. If it's a version issue (as i see mentioned below) i'm not sure what version to change to. We're currently on 5.7.29. 

`(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE
            status NOT IN ('finished', 'error')
            and job_group ' at line 3
)
  
[2020-03-19 09:59:34] udoit.ERROR: Error locking job, rolling back db.  Error contents:\r\nArray
(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE status = 'new' ORDER BY id LIMIT 1 FOR UPDATE' at line 1
)
  
[2020-03-19 09:59:34] udoit.ERROR: Array
(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE
            status NOT IN ('finished', 'error')
            and job_group ' at line 3
)
`

**Comment by bagofarms** [comment]
Can I get some details about your setup?  Specifically:

- UDOIT version
- Operating system and version
- Database software and version
- `$db_type` from your `local_config.php` file.

**Comment by masantiago-wpi** [comment]
Sure:

  *   UDOIT 2.62 (pulled down via Git last week)
  *   Ubuntu 16.04.1
  *   MySQL 5.7.29-0ubuntu0.16.04.1
  *   $db_type = 'mysql';



Thanks for helping me with this.

**Comment by masantiago-wpi** [comment]
I did a line by line comparison between the localConfig file and one from the git repo and saw that in copying over the DB information i dropped one of the lines regarding job_queue. adding it back in, downloading the xml extension for php7.1 seemed to fix just about every error.
