### ISSUE TITLE
Store errors/suggestions in database rows in addition to the fully-generated reports stored on the server.

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#5]
This will allow for analytics like most common error/suggestion, course with the most errors, etc.

**Comment by bedmison** [comment]
This would be a great help in trying to figure out how widely faculty are testing for accessibility issues in their courses. This is a major emphasis for us (the president of the university is pressing this), so this type of admin report would be excellent.

**Comment by bagofarms** [comment]
This will be added with the release of v3.0.0
