### ISSUE TITLE
Missing: oauth_consumer_key 

### ISSUE THREAD

**Issue by masantiago-wpi** [ucfopen/UDOIT#500]
Hi, 
After going through an upgrade process i've had some interesting problems arise. One of them is relating to the LTI information. In the process of troubleshooting i've actually gone through the whole setup on the canvas side:

- deleting the old LTI info

- configuring new one,

- copy and pasting consumer key and secret from config file (this is self hosted on ubuntu server). 

I've tripple checked the values. Is there something else i'm missing? developer keys where also reset and i get as far as clicking the scan button.

**Comment by bagofarms** [comment]
Are you getting the `Missing: oauth_consumer_key` error?  If so, I don't think you'd even get to the scan button.

**Comment by masantiago-wpi** [comment]
I would think that as well but i was able to go through the process and hit the scan button. When I visit the font page for the site I also get this error: Missing LTI launch information. Please ensure that your instance of UDOIT is installed to Canvas correctly. Missing: oauth_consumer_key

In my other issue (which you also helped point me on my way on) the LTI error comes up first on the log but then it goes into other DB errors I’m still tracking down.

**Comment by bagofarms** [comment]
Are you viewing UDOIT through Canvas?  The error message you're seeing is consistent with viewing UDOIT directly (outside of Canvas), and the error is normal behavior in that instance.

**Comment by masantiago-wpi** [comment]
Hi thanks for responding so quickly! I had to take the day off yesterday so i'm just getting back to this, I need to have this up and running by monday. 
So, to answer your question, we're using it in canvas but that error was being displayed in two contexts. 
1) When i visit the index page on the server hosting the UDOIT instance
2) when i run the log after hitting the scan button in canvas.
  [2020-03-17 16:27:51] udoit.ERROR: Missing LTI launch information. Please ensure that your instance of UDOIT is installed to Canvas correctly. Missing: oauth_consumer_key

**Comment by bagofarms** [comment]
Hmm... What is `$background_worker_enabled` set to in `localConfig.php`?

**Comment by masantiago-wpi** [comment]
/* Background worker Options (See Background Workers in Readme) */

$background_worker_enabled = false;

$background_job_expire_time = 20; // after x Minutes, mark job as expired

$background_worker_sleep_seconds = 7;

**Comment by masantiago-wpi** [comment]
I did a line by line comparison between the localConfig file and one from the git repo and saw that in copying over the DB information i dropped one of the lines regarding job_queue. adding it back in, downloading the xml extension for php7.1 seemed to fix just about every error.
