### ISSUE TITLE
Graded discussions showing up under both assignments and discussions

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#505]
If a discussion is graded, there is also an assignment associated with it.  When this assignment is accessed through the API, the discussion data is accessed, making it appear in both places.  This may also affect quizzes.

I suggest having graded quizzes and discussions only show up in quizzes and discussions, respectively.

**Comment by bagofarms** [comment]
TidyUP makes them show up just as Discussions.

**Comment by jasonmatos23-git** [comment]
Closed by #591
