### ISSUE TITLE
Add support for Kaltura videos

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#506]
If the institution uses Kaltura for video hosting, detect if those videos have captions.

**Comment by bagofarms** [comment]
@cidilabs It looks like this might be supported by phpally now. Can you confirm so I can close this issue?

**Comment by cidilabs** [comment]
I'm going to let @atarisafari reply, since he can speak better to the Kaltura integration.

**Comment by atarisafari** [comment]
@bagofarms Yes, we did indeed add Kaltura support to phpally. In order for Kaltura videos to be scanned, you'll need the `KALTURA_API_KEY` and `KALTURA_USERNAME` properties in either the .env or in the Institution table of the database.

**Comment by bagofarms** [comment]
Awesome!  Thanks for the quick reply.
