### ISSUE TITLE
Accessibility issues found in review of 2.6.0

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#516]
From Michelle Tuten at Clemson University:

This test was done with NVDA and FireFox. It is possible that some of these issues related to the "View old reports" section were fixed in the move from 2.6.0 to 2.6.1, but I doubt it was many. Anything related to the "U Fix It" interfaces definitely occur in 2.6.1.

[Survivable] In the UDOIT LTI, the Content and Scan for checkboxes would benefit from being put in a grouping so that when someone Tabs to the Select All checkbox, it is obvious what the Select All applies to.

[Surviviable] Scan Course and View Old Reports tabs are not constructed like a normal tab panel. This may be ok, but because screen readers will say something like Tab 1 of 2, it may be a good idea to reinstate the normal tab panel navigation or, if possible, combine the current access means with the expected access means (allow the second tab to be reached with the Tab key AND the directional arrow keys.). 

[Survivable] In the “What Does UDOIT Look For?” pop-up, there are a lot of “More Info” buttons. When a screen reader pulls up a list of links on the page, there will be no way to tell which More Info goes with which criteria as things are currently. If it is possible to visually hide the criteria in the More info link and audibly hide the visible duplicate text, that might be one way to get around this.

[Potentially Critical] When a More Info button is pressed, there is no expanded/collapsed state verbalized by screen readers.

[Critical] After the Start Scan button is pressed, the screen reader gives no audible clues that anything is occurring and the “Please stay on this page...” warning is not read aloud.

[Potentially Critical] Whether the scan succeeds or fails, there is no audible cue of completion.

[Potentially Critical] In the View Old Reports table, there is no verbal indication that anything in the table is clickable. Also, the links to the reports are not in the tab order.

[Suggestion] Put the date and time the scan was conducted somewhere near the top of the report.

[Survivable] A heading level is skipped between the Summary heading and the Errors heading.

[Survivable] When zoomed in, the content type (h2) heading and the processing time sometimes overlap.

[Survivable] Since the Report Summary is a list of errors, it may be appropriate to move the numbers to the end of the list item’s reading order so as not to be confused for parts of a numbered list.

[Potentially Critical] When the plus signs and “View the source of this issue” buttons are clicked to expand a region, the expand/collapse state isn’t verbalized.

[Potentially Critical] The pop-overs explaining why the U Fix It! buttons are disabled do not have strong enough color contrast.

[Potentially Critical] The “Due to LMS limitations, UDOIT is unable to scan this section…”message in the Syllabus section when there was no content added to the Syllabus page is misleading and can lead to panic. Perhaps a message saying, “UDOIT could not scan this section because either the Syllabus was provided as a document elsewhere in the course or this course does not have content in its Syllabus page.” 

[Potentially Critical] The Read our FAQ link in the Syllabus error message doesn’t have strong enough color contrast.

[Potentially Critical] The “linked image does not have text alternative” error is also accompanied by the “image has no alt text” and the “link has no link text” errors. To prevent errors, it may be appropriate to add some help text to the “linked image….” error to help users use the U Fix It button on only one of the accompanying errors and to help them choose the correct one.

[Potentially Critical] When the “U Fix It!” button is pressed, the expanded state isn’t verbalized.

[Critical] Placeholder text is used to label text fields in the “U Fix It” interface. Those with cognitive impairments may have difficulty filling out these fields if they have trouble remembering what is supposed to go into these fields as they try to complete it.

[Critical] When the foreground or background color field is changed in the color contrast “U Fix It!” region, the ratio validity statement is not verbalized to inform the screen reader user if t their color selection is appropriate. I would also consider changing the reading order of this region and get rid of the color palette unless you know of a use case where the color picker pop-over is insufficient. 

[Critical] In the alt text “U Fix It”, the character limit is not verbalized when focus is on the form field.

[Scanning Error] For some reason, some links in the course used for testing (“Click to Enroll in this course” and “Feedback and Updates”--a Canvas page on where to share feedback and update) were flagged as not having captions when they are not in any way associated with videos. 

[Scanning Error] Also, on, for example, the page about video captioning, I have a link to a separate Canvas page that was flagged as having “captions are not in video language.” When I visit that link, I have a dead YouTube video and an Amara tutorial video linked on the page. When I get to this page in the UDOIT report, it flags the linked dead YouTube video. So it is like I’m getting layered errors for a single error and I don’t even think the error is accurate.

[Incorrect messaging] When 2.6.1 is opened in Firefox, I get the following message: “Welcome to UDOIT on Safari. Please click the button below to set up this tool for use with Safari. Setup UDOIT.” Clicking the button causes the page to refresh then shows the message again until the page has had enough time to load to bring up the interface. This was confusing on a couple of levels. 1) I’m not in Safari. 2) Seeing the message for a second time made me think this was stuck in a loop until I saw the loading icon in the browser tab. If I had been blind, I would have thought the tool was broken.

**Comment by bagofarms** [comment]
Fixes for these issues will not be implemented in 2.x, but I am reassigning this to 3.1.0 so that we can evaluate whether these issues are still valid in 3.x

**Comment by AlanFCMV** [comment]
The majority of these have been resolved in UDOIT 3.0. I have opened new issues to tackle the ones remaining.
#652 
#653
