### ISSUE TITLE
PHP 7.3 session cookie param 'lifetime' instead of 'expire' 

### ISSUE THREAD

**Issue by escull75** [ucfopen/UDOIT#535]
@bagofarms 
See:
https://github.com/ucfopen/UDOIT/blob/bb09555bec4dee58e26a856a2b1e6646ecefb63d/config/settings.php#L42

We hit errors with this on our server; I believe the correct key for the first value in the session_set_cookie_params() configuration array is 'lifetime' instead of 'expire':
https://www.php.net/manual/en/function.session-set-cookie-params.php

**Comment by bagofarms** [comment]
Thanks!  I had already created an issue for this #530, pull request #531 , and I've fixed it in the upcoming 2.6.4 release #534

**Comment by escull75** [comment]
Beautiful, thanks!
