### ISSUE TITLE
Update Httpful library version number

### ISSUE THREAD

**Issue by chrispittman** [ucfopen/UDOIT#539]
The current version of Httpful (`~0.2.20`) is missing a [bug fix](https://github.com/nategood/httpful/blob/v0.3.2/src/Httpful/Request.php#L521) for people who run UDOIT behind a proxy and who use the `http_proxy` environment variable.

Please consider updating to `~0.3.2`.

**Comment by bagofarms** [comment]
Thanks for reporting this!  We'll update it in the next release.

**Comment by bagofarms** [comment]
Merged into dev/v2.7.1
