### ISSUE TITLE
UDOIT Error in Canvas Using Chrome

### ISSUE THREAD

**Issue by kcmorg** [ucfopen/UDOIT#544]
Our faculty are reporting a "Missing Session Information.  Please refresh the page.  Missing: base_url" error when trying to use UDOIT on a Chrome browser.  I have checked the Canvas community and Google search for an answer to this, but can't seem to find why this is happening?  It works fine when using FireFox or Edge.  Any ideas on why this is failing on Google Chrome?

Thanks!

Jeff Morgan

![UDOIT_Chrome_Error](https://user-images.githubusercontent.com/44170391/91054917-8e8d7f80-e5e9-11ea-9e16-4fb61070233e.jpg)

**Comment by bagofarms** [comment]
Please see my response to #543
