### ISSUE TITLE
Unable to trigger "Multimedia objects should have text equivalents" with example code

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#562]
From Michelle Tuten:
A few things with "Multimedia objects should have text equivalents (e.g. transcripts)"
- When attempting to intentionally break this rule, I copied the example from "More Info" and couldn't get the error.
  - I love that an example was included in the More Info so that I could easily copy it into the Canvas course for testing. Could that be done for all of them? Or else, a Canvas page created, added to Commons, and linked to UDOIT be made for easy testing?  
- Looking back in my old reports just now, I see that I was able to trigger this result during one of the failed scans, but it was applied to something in an <object> tag that doesn't actually render and only exists in this course because I was previously able to trigger an old result with it.

**Comment by jasonmatos23-git** [comment]
Issues #101 and #102 are both relevant to NG, although they should have already been closed for classic.
