### ISSUE TITLE
Implement testing for UDOIT w/ PHPUnit

### ISSUE THREAD

**Issue by techrangerfj** [ucfopen/UDOIT#59]
This should be realized by installing PHPUnit via composer and implementing unit tests for internal UDOIT functions.

**Comment by techrangerfj** [comment]
Low level unit tests implemented and merged with recent pull request (https://github.com/ucfcdl/UDOIT/pull/176)

What remains are tests for internal scanning procedure and overall api logic.

**Comment by bagofarms** [comment]
This is a constant thing, so i'm going to close this issue.
