### ISSUE TITLE
Add the ability for users to ignore certain suggestions

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#6]
For instance, if a course has a lot of videos that they have checked for closed captions, allow the user to ignore video errors/suggestions so that they can focus on the other errors/suggestions for now.

**Comment by bagofarms** [comment]
We could also allow the user to ignore specific errors,  One example is an image attribution and licensing blurb that contains the URL for the license.  It needs to be a URL rather than a text link just in case the page is printed, so the instructor will never satisfy the error in UDOIT.

We would also need a way for users to "unignore" these errors in the future.

**Comment by techrangerfj** [comment]
Do you want the error to no longer appear in the on screen report? the printed pdf? Or the course all-together moving forward? @bagofarms

**Comment by bagofarms** [comment]
@techrangerfj it should not appear in the course moving forward, but there needs to be some kind of interface that shows which types of errors/suggestions were hidden so that the user can re-enable them if they want.

**Comment by bagofarms** [comment]
Also add banner at the top of the results that would warn the user that they are ignoring certain errors.

This data needs to be mapped to the course and user, so that other users going into that course won't have the same ignore settings.

Also, each instance of that error should have a link or some way to ignore others of that type, just to make it easier on the user.

**Comment by bagofarms** [comment]
We could write an attribute to the element containing the date it was hidden.  The expiration of the "hide" could be configurable.  Still include these hidden items in the report, but minimized or filtered out through something like #497 .

**Comment by bagofarms** [comment]
#497 #498 addresses this.  I don't think we'll be able to get much better than that, so I'm closing this
