### ISSUE TITLE
Add UFIXIT for pNotUsedAsHeader (Avoid using styles for document structure)

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#60]
The UFIXIT for this should allow the user to choose a heading for the text:  H2, H3, and H4

I would include H5 and H6, but the Canvas editor doesn't support them.  Should we include them anyway?

**Comment by techrangerfj** [comment]
@bagofarms during our meeting, it was decided to end at H4. I'll work on this now.

**Comment by bagofarms** [comment]
Fixed in 2.6.0
