### ISSUE TITLE
2.8 - H2 flagged as a skipped heading

### ISSUE THREAD

**Issue by cidilabs** [ucfopen/UDOIT#622]
Cidi Labs received this feedback from Khaled Musa at UMN:

Just wanted to alert you that skipped headings marks all pages that have a heading level 2 as skipped headings and the accompanying message doesn’t factor that Canvas  doesn’t allow anyone to add heading level one since it is the title of the page.
When a page starts with a heading level 2 it shouldn’t alert the user that it is a skipped heading unless the one after level 2 is 4 .
The message with the error alert should add that heading level 1 is reserved by canvas for the page title.
Please let me know if you need a page to replicate this error.

**Comment by bagofarms** [comment]
This is now fixed in [UDOIT 2.8.1](https://github.com/ucfopen/UDOIT/releases/tag/v2.8.1)
