### ISSUE TITLE
2.8 version bogging down production server when scanning a larger course

### ISSUE THREAD

**Issue by cidilabs** [ucfopen/UDOIT#627]
Scanning a larger course brings the entire server to a halt on 2.8. This is most likely due to the link validation being done with Curl. Investigation needs to be done to see if there's a more efficient, less processor and memory intensive way to do this.

**Comment by cidilabs** [comment]
The issue was found in the handling of pagination of API calls with results greater than 100. The code was adding `&page=1` to the end of the API query, which continued to return the same page endlessly in a do/while loop. 

The fix: 
```
if (strpos($url, 'page=') === false) {
    $url .= "&page={$cur_page}";
}
if (strpos($url, 'per_page=') === false) {
    $url .= "&per_page={$per_page}";
}

$response = static::apiGet($url, $api_key)->send();
```

**Comment by bagofarms** [comment]
@cidilabs Would this code be a replacement for this line? https://github.com/ucfopen/UDOIT/blob/classic/lib/Udoit.php#L556

**Comment by cidilabs** [comment]
Yeah, sorry for not making that clear. It just verifies those query params don't already exist before adding them on.
