### ISSUE TITLE
Fresh install of 3.0 infinitely scanning on first open

### ISSUE THREAD

**Issue by jasonmatos23-git** [ucfopen/UDOIT#640]
After installing 3.0 on Heroku with a fresh database, the initial scan runs infinitely. I must refresh the page in order to get the scan to complete and be able to hit the 'Continue' button.
![Screen Shot 2021-09-03 at 2 38 05 PM](https://user-images.githubusercontent.com/58221112/132060646-0596905c-1404-465c-a806-8c2521f32826.png)

**Comment by jasonmatos23-git** [comment]
This is what displays in the inspector.
![Screen Shot 2021-09-03 at 5 32 14 PM](https://user-images.githubusercontent.com/58221112/132067262-9d7fc671-d154-4155-a693-6a1d98d2b241.png)

**Comment by bagofarms** [comment]
@jasonmatos23-git Have you been able to find where this TEST message is coming from?

**Comment by cidilabs** [comment]
Can we re-test this? I believe the "TEST" was being printed in PhpAlly when certain configurations were missing. This has been fixed.
