### ISSUE TITLE
Authorization token not being refreshed properly

### ISSUE THREAD

**Issue by AlanFCMV** [ucfopen/UDOIT#648]
After an hour I am forced to manually reauthorize UDOIT.

**Comment by cidilabs** [comment]
Can you provide more detail? Was the page open for longer than an hour and require a page reload after that? What do you mean by "manually reauthorize"?

**Comment by jasonmatos23-git** [comment]
@cidilabs Prior to #619, if the access token was deleted from within Canvas, the app would spend 30+ seconds loading and then crash on Heroku. That PR ignores an unauthorized response (401) which allows the user to re-authorize udoit. But it also forces them to re-authorize every hour after the access token expires. #659 is undoing that PR and attempting another fix involving a timeout when refreshing the API key.
