### ISSUE TITLE
Assistance Authentication Issue

### ISSUE THREAD

**Issue by tjalway** [ucfopen/UDOIT#696]
Hello,

I am having an issue with some users being able to authentic to when trying to run UDOIT.  Unfortunately we are still using version 2.5.  It seems that anyone who was added as a user in Canvas recently is not able to authentic.  The exact message is "Authentication Problem: please contact support."

Secondly, I was wondering if there was a video on how to install UDOIT version 3, similar to one that was created for version 2.5?  I am very unfamiliar with using GitHub and Heroku.  A lot of the information provided to me does not make sense.  Would it be possible to obtain some assistance in that area?  I was able to deploy the instance of UDOIT on Heroku but beyond that the instructions become cloudy.

Thank you.

T. Alway

**Comment by bagofarms** [comment]
The error message you're seeing in 2.5 means that Canvas is not providing the proper information during the final step of the authentication process.  Most likely, your developer API key is not working correctly anymore.  I've seen this happen to other institutions, and the solution was to generate a new developer API key and set up UDOIT with that new information.

We don't have a video for installing UDOIT 3.0.0 yet, as we're still refining the installation process.  What issues or questions did you have about the Heroku installation process?  Maybe I can clear them up and make the documentation better.

**Comment by tjalway** [comment]
Hello Jacob,

Thank you for your quick response to my question.  I created a new developer key but so far have not been able to resolve the issue.  Knowing that this may be the cause of the issue, I am continuing to look in that area.  It is possible that I may have not completed those steps properly (user error).  I was in a rather rush when trying to do so.

Regarding UDOIT 3.0.  I am using Heroku for my web server.  Therefore I followed the instructions to automatically deploy to Heroku.  After this step I get lost.  I then went to the instructions in “INSTALL_CANVAS.md”.  I assume that because I am using Heroku, I can skip the section titled “Docker-Compose Base.  However, the next step is where I get tripped up.  Under the heading “Update the Institutions Table”, I don’t know where to go to find this.  Since I am using Heroku as my web server, I have nothing installed at my institution.  Should I?  Beyond that, the final two steps make sense.  I hope that helps to describe my trouble.  Please let me know if you need further clarification.

Sincerely,
Tom Alway
Tom Alway, BS-AET, MS-ITM
Learning Management Systems Analyst
West Shore Community College
3000 North Stiles Road | Scottville, Michigan 49454
Phone: 231-843-5967

**Comment by AlanFCMV** [comment]
The institutions table can be found in the database. It is not something installed at your institution, but rather information about your institution stored in the database. You will want to access the UDOIT database through Heroku and insert your institution's information into the table. Instructions on how to set up and access the database on Heroku can be found [here](https://github.com/ucfopen/UDOIT/blob/main/HEROKU.md#step-3-database-migration-and-setup). Please let me know if you need more assistance.

**Comment by tjalway** [comment]
Hello Alan,

Sorry for the lengthy delay in getting back to you.  I have been attempting to work through the installation guides but to no avail.  I am getting tripped up at Step 2: Clone UDOIT and Push to Heroku in the HEROKU.md document.  It just does not make sense to me.  I even had a colleague of mine look at it and he too was stumped.  Step 1 of this section redirects me to follow the Source Code section of the INSTALL.md document.  In that section, I confirmed that I have Git installed on my server, which is Heroku.  However, I cannot find the directory where UDOIT lives.  When I try changing directories, it does nothing.  Where should I be looking?

Also,  I am assuming that once the steps under the Source Code section are completed then I am to return to steps 2, 3 and 4 under Step 2: Clone UDOIT and Push to Heroku.

Sorry to bother you but my current instance of UDOIT, ver 2.5, is not working and faculty are demanding that I resolve it asap.  I figured that the best to fix it was to install the newer version.  But it’s beyond anything that I have ever done before.

Sincerely,
Tom Alway
Tom Alway, BS-AET, MS-ITM
Learning Management Systems Analyst
West Shore Community College
3000 North Stiles Road | Scottville, Michigan 49454
Phone: 231-843-5967

**Comment by bagofarms** [comment]
@tjalway Our next release will have better instructions for Heroku.  [Please take a look at them](https://github.com/ucfopen/UDOIT/blob/dev/v3-1-0/HEROKU.md) and see if they make more sense.  We would love your feedback on it before the next release.

**Comment by tjalway** [comment]
Thank you.  I will do that.

**Comment by tjalway** [comment]
Hello Jacob,

First off, well done on the revision.  I was able to follow it and was able to successfully get UDOIT v3 working.  If I can do it, anyone can.  The instructions are very specific where you need to reference additional documentation.  The access to the database made sense to me.  It is a much cleaner format.

I very first time I ran UDOIT I got a message at the top of the screen that said “Failed API call.”  I revisited my API settings in Canvas and everything seems to match.  I moved out of UDOIT and came back into it and did not get the error.  It might have been waiting for Heroku to spool up.  Otherwise it appears to be working.  Now on to learning the nuances of the newer format.

Thank you again for all of your assistance.  I greatly appreciate it.

Sincerely,
Tom Alway
Tom Alway, BS-AET, MS-ITM
Learning Management Systems Analyst
West Shore Community College
3000 North Stiles Road | Scottville, Michigan 49454
Phone: 231-843-5967
