### ISSUE TITLE
Heroku deployment failing

### ISSUE THREAD

**Issue by UoHdigitallearning** [ucfopen/UDOIT#708]
I am trying to use the Heroku install button, however I am getting a recurring error at the Run scrypts and scale dynos. All of the fields are correctly filled. Any ideas? Am not particularly technical sorry but will try and field any follow ups :-)

![image](https://user-images.githubusercontent.com/52406705/140768427-c1d858c8-9945-4d56-8a1c-36bae2f04885.png)

**Comment by bagofarms** [comment]
I see the problem.  We're using the same syntax for MySQL and PostgreSQL, but the PostreSQL version should probably be
```pgsql
ALTER TABLE users ALTER COLUMN id TYPE bigint
```
I'm pretty busy right now, so it might be a few days before this fix goes through.  Is there a reason why you're using the Classic version of UDOIT instead of the latest?

**Comment by bagofarms** [comment]
Interesting.  That button should be pointing to the latest version.  When did you click it?  I just tried the button on that page, and it was using the correct code.

**Comment by bagofarms** [comment]
Unfortunately, the installation process for UDOIT 3 is more complex, so it requires some technical support on your end.  We are still refining the installation process, so we might be able to simplify it in the future.

In the meantime, you can still use "classic" UDOIT.  I have fixed the migration, so clicking the Heroku button on the [classic README](https://github.com/ucfopen/UDOIT/tree/classic) should work now.

**Comment by UoHdigitallearning** [comment]
Thank you so much. Will have a go with classic and find the support from somewhere across our university to do the upgrade. Thanks again
