### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by phillyc** [ucfopen/UDOIT#71]
Some notes about the README based on my run through the initial setup of this tool on my local machine.

I think it would be useful to include a list of things you'll need to get started, including:
- A development instance of Canvas (or production if you're brave)
- MySQL installed (with version?)
- Any other dependencies.

Some general questions I think could be answered in the README:

"What are my options for development or testing?" (Heroku, local, etc)
"Can I run this against a test instance of Canvas? How?" (at least provide a link to an external resource)

We should probably move the class and method stuff into the wiki.

"How do I get started with automated testing?"

**Comment by bagofarms** [comment]
We have added all of this in some form over the years.  Thanks again for testing this out, Phil!
