### ISSUE TITLE
Node version requirement for yarn build

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#714]
When you run `yarn build` with npm version 17.x.x, it stops with a syntax error at 10&.  However, if you use npm version 15.11.0, it does work.  This needs more research.

**Comment by rob-3** [comment]
I can't reproduce this. Are you still having this issue?

**Comment by rob-3** [comment]
Just got this issue while continuing to work on Dockerizing. I believe the relevant bug is https://github.com/webpack/webpack/issues/14532. The solution is to use set `export NODE_OPTIONS=--openssl-legacy-provider`. Reopen if that doesn't resolve this.
