### ISSUE TITLE
Improve Installation Instructions

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#732]
## 1. Composer Dependencies
The current instructions in [Installing Composer Dependencies in INSTALL.md](https://github.com/ucfopen/UDOIT/blob/main/INSTALL.md) direct the user to use the host machine's version of PHP to install the compose dependencies.  Instead, I recommend we change the instructions to download composer and run the install command from inside the PHP container.  Something like this:

1. [Download Composer](https://getcomposer.org/download/) to the root directory of UDOIT.
2. Run `docker-compose up -d` if it isn't already up.
3. Run `docker exec -it udoit_php_1 /bin/bash`
4. Run `php composer.phar install --no-dev`

## 2. ENV Setup
* Update `.env.local.example` so that the `DATABASE_URL` value is `mysql://root:root@db:3306/udoit3`
* Clarify that the `APP_ENV` should stay `prod`

## 3. Database Setup
Clarify that you should be inside the docker container before you run the commands.

## 4. Javascript
Clarify that you should be inside the docker container before you run the commands.

**Comment by SimonRothUCF** [comment]
The new instructions look good to me; they're clear and cover everything above. Does `.env.local.example` need to be updated?

**Comment by bagofarms** [comment]
The PR includes changes to `.env.local.example`, so I think we're good.
