### ISSUE TITLE
Unable to use hardcoded value of JWK_BASE_URL for beta/test installs and multiple instituions

### ISSUE THREAD

**Issue by jonespm** [ucfopen/UDOIT#740]
In testing this, it seems like there is only one hardcoded environment variable `JWK_BASE_URL` for all hosted institutions to use in https://github.com/ucfopen/UDOIT/blob/d19ef66a7fd70d45f85d17b1ba1ec6e4c3a64f65/src/Lms/Canvas/CanvasLms.php#L79

The value by default goes to https://canvas.instructure.com/api/lti/security/jwks and this seems to match the keys generated by the **production** Canvas installation for launch.

However in the **beta** and **test** instances, it looks to require use of the domain which is

`$baseURL = $this->util->getCurrentDomain();`

This would go to this, similar to other calls
`https://${baseURL}/api/lti/security/jwks`

I think we'd either need to

*  Always use this as the `$baseURL` for all instances, it works fine for production and you don't need to go to the generic canvas.instructure.com URL
* Use a specific `JWK_URL` for each institition, defined in the database institution table.

**Comment by jonespm** [comment]
Well the problem is that in two places it's not looking up the domain, that's where the code isn't work for me, at least not in test and beta. The KID that Canvas generates for those instances doesn't match the one on https://canvas.instructure.com/api/lti/security/jwks which is what's being used by the code.

You can change the ENV to point to test, but then it won't work with production.

I've found just removing use of this ENV and using the `/api/lti/security/jwks` from the calling host _seems_ works in all cases and this ENV is unnecessary. I'm not sure if this needs to be configurable in the database or not on the institution.
 
https://github.com/tl-its-umich-edu/UDOIT/compare/4c6777ddcf50e40ef929ef7b83be17afd8818bcc...tl-its-umich-edu:431e700922bf880ca45e21ce3db64b7bf74d08f2

**Comment by rob-3** [comment]
That seems like a reasonable approach. I can't think of a case where this wouldn't work and the `JWK_BASE_URL` variable otherwise seems relatively useless. I'll get a PR up and run it by my coworkers

**Comment by rob-3** [comment]
Just tried this and it broke our testing setup.

**Comment by jonespm** [comment]
Hmm, what instance of Canvas is your test running on? 
The canvas.instructure JWKS https://canvas.instructure.com/api/lti/security/jwks 
matches our prod https://umich.instructure.com/api/lti/security/jwks
and the UCF one https://webcourses.ucf.edu/api/lti/security/jwks

But doesn't match our test https://umich.test.instructure.com/api/lti/security/jwks
or beta https://umich.beta.instructure.com/api/lti/security/jwks 

Which is where this problem comes in. I know this URL is also defined in the LTI Developer Key on Canvas but that doesn't *seem* to be used by the launch.

**Comment by jonespm** [comment]
Hmm, it looks like that URL does exist there
https://canvas.dev.cdl.ucf.edu/api/lti/security/jwks

I think you'd have to [decode your JWT](https://jwt.io/) from the failed launch to see why it isn't working. 

Maybe we need an environment variable like USE_CURRENT_DOMAIN_FOR_JWKS or something? In an earlier version of the fix I had set JWK_BASE_URL to empty and did check to see if it was empty. But if you don't define it, I believe it picks up the default from the [.env](https://github.com/ucfopen/UDOIT/blob/d19ef66a7fd70d45f85d17b1ba1ec6e4c3a64f65/.env)?

**Comment by bagofarms** [comment]
> Hmm, it looks like that URL does exist there
That URL is an internal test instance of Canvas, and is not accessible to the outside world.  We have used that jwk url successfully in the past.  I need to do some more research on this in order to make an intelligent response, though.  Maybe @ssilverm has a suggestion.

**Comment by jonespm** [comment]
I was looking at some other LTI 1.3 implementations 
PyLTI1.3 (Python) [has the JWKS URL](https://github.com/dmitry-viskov/pylti1.3/blob/476556aa5b13da20be591b6aea4b4f61b85ea8fe/pylti1p3/contrib/django/lti1p3_tool_config/migrations/0001_initial.py#L52) stored in the database for each tool. 
The example[ PHP app](https://github.com/IMSGlobal/lti-1-3-php-example-tool/blob/523bba29a8dba3f9793d3630318d8182ec7074ab/src/db/example_database.php#L22) that uses the IMS PHP library also has it in the database. So I guess that'll end up being the way to go, storing the **key_set_url**. Thought it would have been a little simpler without a schema change.

It looks like the [PHP also has JWKS endpoint as part of the tool](https://github.com/IMSGlobal/lti-1-3-php-library/blob/master/src/lti/JWKS_Endpoint.php) but the setup for Python has you manually generate this and paste it in to Canvas.

**Comment by rob-3** [comment]
Some progress - `$this->util->getCurrentDomain()` seems to return `"canvas.instructure.com"` with our configuration, which is a bug. Hardcoding the correct domain fixed my issues. I'm going to look into exactly what that function does and figure out why it isn't working.

**Comment by rob-3** [comment]
@jonespm, #744 is the intended resolution for this issue. I removed `$this->util->getCurrentDomain()` entirely in favor of a `LMS_BASE_DOMAIN` environment variable that is always used.

**Comment by rob-3** [comment]
@jonespm #747 fixes this and will land in 3.2.0. Just set your `JWK_BASE_URL` to the empty string or remove it altogether.
