### ISSUE TITLE
Only send lti_message_hint if it exists 

### ISSUE THREAD

**Issue by ottenhoff** [ucfopen/UDOIT#746]
> 4.1.1 lti_message_hint login parameter
> The new optional parameter lti_message_hint may be used alongside the login_hint to carry information about the actual LTI message that is being launched.
> 
> Similarly to the login_hint parameter, lti_message_hint value is opaque to the tool. If present in the login initiation request, the tool MUST include it back in the authentication request unaltered.

**Comment by rob-3** [comment]
We do use this parameter; is this issue just about not sending it with an empty value if it wasn't present in the initiation request?

**Comment by ottenhoff** [comment]
Correct. It should not be sent back to LMS if empty
