### ISSUE TITLE
variable passed by reference error

### ISSUE THREAD

**Issue by robfentress** [ucfopen/UDOIT#77]
Using a plain vanilla scotch box (https://box.scotch.io/), I got an "Only variables should be passed by reference" error for line 21 on udoit.xml.php.

The original line of code was:

``` php
    $scriptname=end(explode('/',$_SERVER['PHP_SELF']));
```

Changing it to the following resolved the issue:

``` php
    $exploded = explode('/',$_SERVER['PHP_SELF']);
    $scriptname=end($exploded);
```

I guess it would work if you turned off strict, but would probably be better if this was changed in the codebase.

**Comment by bagofarms** [comment]
I thought for sure i had fixed that issue before.  I'll mark it as a bug.  Thanks!

**Comment by techrangerfj** [comment]
@bagofarms This is already in the codebase

**Comment by robfentress** [comment]
I don't see it here: https://github.com/ucfcdl/UDOIT/blob/master/udoit.xml.php

Is there another place I should be looking?

**Comment by bagofarms** [comment]
@robfentress @techrangerfj I don't see it in the codebase, either.  It's a simple change, so i'm going to roll it into the next pull request i do, which should be soon.

**Comment by cooperfellows** [comment]
This looks like it's all done, we should be able to close this out:
 - https://github.com/ucfopen/UDOIT/blob/master/public/udoit.xml.php#L25
 - https://github.com/ucfopen/UDOIT/commit/6c8308991c818d296a6783a536c74423234da55f#diff-ce0febea1216298bb7992a167aede281R21

`$exploded   = explode('/',$_SERVER['PHP_SELF']);`
`$scriptname = @end( $exploded );`

**Comment by bagofarms** [comment]
Agreed!
