### ISSUE TITLE
UFIXIT Review modal becomes unusable if the preview content is a Canvas Studio video

### ISSUE THREAD

**Issue by mrash2** [ucfopen/UDOIT#814]
In our instance of UDOIT 3.2, we're finding when an issue is raised due to external content (specifically, an embedded Canvas Studio video), the Review modal that pops up initially populates with content, but then becomes unusable due to the Canvas server refusing to connect. I imagine this is because it is essentially an iframe within an iframe. The only way to proceed is to close the modal or continue clicking Next/Prev until another issue appears. However, there doesn't seem to be a way to manually resolve the original issue in question.
![image](https://user-images.githubusercontent.com/59924812/168128206-208bdea6-0e6f-43b3-9cab-ef9427d6681f.png)
![image](https://user-images.githubusercontent.com/59924812/168128230-fa617a63-7378-4788-bab5-aa17435ef351.png)

**Comment by bagofarms** [comment]
Unfortunately, UCF does not have access to Canvas Studio to test this out or develop a solution.

**Comment by mrash2** [comment]
Thanks for the info.
