### ISSUE TITLE
Feature request: bulk resolve

### ISSUE THREAD

**Issue by mrash2** [ucfopen/UDOIT#828]
Have you considered adding a feature to mark issues as resolved in bulk? For example, we often have instructors who copy and paste content from elsewhere to put into a Canvas page. That may pick up some CSS styling that causes UDOIT to flag it for something like not using color alone for emphasis. One instructor has literally hundreds of these pages. Is there a way or planned way for the user to select multiple instances of this issue and mark them as resolved?

**Comment by bagofarms** [comment]
I'm cautious about this kind of feature. Manual resolution implies that you have viewed the content and verified that it is accessible before checking the box.  If content has been copied from various sources, I think the instructor should evaluate every page to make sure it is accessible before marking it resolved.  Is it always the same bit of code that's triggering the issue, or is it different every time?

**Comment by mrash2** [comment]
That makes sense. The specific example we’re seeing pop up often is a random span tag with an in-line style applied. I know the users would not have known to add this specific styling, so I’m honestly not sure where it is coming from. Here’s an example:

<span style="color: var(--ic-brand-font-color-dark); font-family: inherit; font-size: 1rem;">…some text…</span>

Your explanation as to why it might be best not to permit bulk resolves sounds reasonable to me. In this instance, I’m not sure how the users got this styling with the CSS variable into their coding. In any case, I understand why UDOIT is flagging this as possible use of color alone for emphasis. Any thoughts on how to handle or prevent this moving forward? Or maybe it is what it is?

Thanks,
-Mark



From: Jacob Bates ***@***.***>
Date: Thursday, July 28, 2022 at 5:46 PM
To: ucfopen/UDOIT ***@***.***>
Cc: Rash, Mark ***@***.***>, Author ***@***.***>
Subject: Re: [ucfopen/UDOIT] Feature request: bulk resolve (Issue #828)

I'm cautious about this kind of feature. Manual resolution implies that you have viewed the content and verified that it is accessible before checking the box. If content has been copied from various sources, I think the instructor should evaluate every page to make sure it is accessible before marking it resolved. Is it always the same bit of code that's triggering the issue, or is it different every time?

**Comment by taheralfayad** [comment]
Since it is deemed to not be the best course of action to implement bulk resolve, we will be closing this issue. To help resolve this issue, I would go with the approach of cleaning the HTML and CSS after the instructor has pasted the content into their page.
