### ISSUE TITLE
Create Helm chart deployment for UDOIT

### ISSUE THREAD

**Issue by bryancpowell** [ucfopen/UDOIT#847]
[Helm](https://helm.sh/) is the standard way to deploy applications to a Kubernetes cluster in many institutions. A Helm chart for UDOIT would enable deployments to Kubernetes to be greatly simplified. Since the release of 3.3.0 includes a fully containerized build of UDOIT, this process is much more tenable.

The Helm chart should be part of this project, with chart publishing handled through GitHub Actions. This process is described in the document [Chart Releaser Action to Automate GitHub Page Charts](https://helm.sh/docs/howto/chart_releaser_action/).

This feature will be handled by Miami University/(miamioh.edu).

**Comment by dmols** [comment]
Based on the comments in the #891 pull request, it doesn't seem like we'll need to make changes on our end. Closing this issue.
