### ISSUE TITLE
Remove db platform from docker-compose.yml

### ISSUE THREAD

**Issue by jonespm** [ucfopen/UDOIT#850]
The platform option in the docker-compose.yml is unnecessary and doesn't work when running under an M1 arm Mac. That line can just be removed.

https://github.com/ucfopen/UDOIT/blob/ff9d7cd76128a2df339351e5268e53bd71b0a25e/docker-compose.nginx.yml#L6

**Comment by ssilverm** [comment]
The platform: linux/amd64 makes it work on M1 Macs if you have Rosetta2 installed.

**Comment by jonespm** [comment]
I believe I have rosetta

When I run `docker compose -f docker-compose.nginx.yml up` it says 

`Error response from daemon: image with reference mysql:latest was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64/v8`

Perhaps because I already have a project that uses the linux/arm64/v8 mysql? I could clean my images I guess but we've got so many docker-compose files that use mysql.

**Comment by jonespm** [comment]
Yeah, ever since the 8.0.29 tag 3 months ago I guess.
![image](https://user-images.githubusercontent.com/27447/194415401-d5352042-ec76-4efa-9b68-8272ffb88478.png)

**Comment by bagofarms** [comment]
@jonespm Feel free to submit this as a PR.  It would qualify for Hacktoberfest if you're participating in it.

**Comment by jonespm** [comment]
Okay, easy enough. I forgot it was that time of year already. Thanks @bagofarms.
