### ISSUE TITLE
GitHub Actions returns "digital envelope routines::unsupported" on build

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#893]
The GitHub Action we have for running tests on pushes and pull requests is currently failing, providing a `digital envelope routines::unsupported` message. [Example](https://github.com/ucfopen/UDOIT/actions/runs/4255788992/jobs/7403849035)

I believe this has happened because the PHP 8.1 GitHub Actions runner has updated to Node 17. There's a [related issue](https://github.com/webpack/webpack/issues/14532) from 2021 that is still active as of yesterday. One user suggested creating a `NODE_OPTIONS` environment variable with the value `--openssl-legacy-provider`, but another pointed out that this may open your application up to using insecure cryptography.

I've identified two solutions so far:
1. Update Webpack to at least 5.61.0. We're currently on 3.3.12, so that would be quite a jump.
2. See if we can force the GitHub Actions runner to use Node 16 instead. I'm not sure how to go about that, though. It also feels like a step backwards.

**Comment by ssilverm** [comment]
Github actions was also degraded yesterday.  They were having an outage.

**Comment by taheralfayad** [comment]
We specified the specific node version that UDOIT runs in the github action [node v16.19.0], which solves this issue.
