### ISSUE TITLE
High False Positive Rate with Avoid Using Styles for Document Structure 

### ISSUE THREAD

**Issue by SavvyDolphin77** [ucfopen/UDOIT#923]
For version 3.3.2

Description: UDOIT seems to falsely report the Avoid Using Styles for Document Structure on text that is bolded but not a heading. 

Suggested/Potential Idea To Fix: Have a check to see if the word count is too long maybe greater than 16 characters (as that would not be any reasonable heading) and if so does not mark the text as a header that should not be bolded. I do not know the inner workings of UDOIT as much so this may not be applicable but is just a thought to consider.

Step by Step to Reproduce:
- Perform a UDOIT scan with content in on a page that has a header and then some bolded text and regular text.
- UDOIT will detect the bolded text and give an Avoid Using Styles for Document Structure despite it not being a header.

Noticed that it is semi-iffy on this after further testing for this bug report. Some instances it won't detect, other times it well. Sometimes if the text is inside a span, it gets flagged and follows same issue here. Other times like in the Example HTML provided it does not. Recommended when fixing an enhance dive into different test cases to see what is trigger it as the one example provide may not cover all false reports that this is affecting. 

Example HTML: 
```
<h2>This is A Header</h2>
<p><strong><span>This is some text that I have bolded because its really important! But unfortunately not as important as a header.</span><br /><br /></strong>text text text text text text text text</p>
<p>&nbsp;</p>
<h3>Header 236</h3>
<p><strong>test text more text more text more text more text more text more text more text</strong></p>
```
If you create a new page, copy and paste the code into the HTML editor, then save, publish, and run in UDOIT it should be flagged or at least was on my end. Again, does not cover all possibilities that UDOIT incorrectly flags bolded text.

The "test text more text more text more text more text more text more text more text" should be falsely reported by UDOIT with the Avoid Using Styles For Document Structure using the above HTML code in a page and as seen in the screenshot below.

<img width="966" alt="Screenshot 2023-10-12 at 16 23 52" src="https://github.com/ucfopen/UDOIT/assets/46875742/5f3dd528-b44b-418c-8c72-050303d70f09">

Severity: Low/Medium (can be worked around by marking as resolved, but still should not be the desired output of UDOIT)
Scale: Large, affects all users with html that has bolded text that is not a heading.

**Comment by taheralfayad** [comment]
The reason that this particular error happens is because UDOIT treats `<p>` tags that only have text content in a `<strong>` tag as potentially a style for heading error. This is the code from phpa11y that performs the check.

**phpally/src/Rule/ParagraphNotUsedAsHeader.php**:
```
if (isset($p->nodeValue) && isset($p->firstChild->nodeValue)) {
    if (($p->nodeValue == $p->firstChild->nodeValue)
	    && is_object($p->firstChild)
	    && property_exists($p->firstChild, 'tagName')
	    && in_array($p->firstChild->tagName, $this->head_tags)
    ) {
	    $this->setIssue($p);
} 
```
Now this is a fair assumption for UDOIT to make, the chances of this actually being an error are high. But I think the description text in the modal should change to something that tells the user to verify that this is an error. @dmols Let me know of any thoughts that you have and we can move to change the description.
